// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dota_gcmessages_client_tournament.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ETournamentEvent int32

const (
	ETournamentEvent_k_ETournamentEvent_None                                      ETournamentEvent = 0
	ETournamentEvent_k_ETournamentEvent_TournamentCreated                         ETournamentEvent = 1
	ETournamentEvent_k_ETournamentEvent_TournamentsMerged                         ETournamentEvent = 2
	ETournamentEvent_k_ETournamentEvent_GameOutcome                               ETournamentEvent = 3
	ETournamentEvent_k_ETournamentEvent_TeamGivenBye                              ETournamentEvent = 4
	ETournamentEvent_k_ETournamentEvent_TournamentCanceledByAdmin                 ETournamentEvent = 5
	ETournamentEvent_k_ETournamentEvent_TeamAbandoned                             ETournamentEvent = 6
	ETournamentEvent_k_ETournamentEvent_ScheduledGameStarted                      ETournamentEvent = 7
	ETournamentEvent_k_ETournamentEvent_Canceled                                  ETournamentEvent = 8
	ETournamentEvent_k_ETournamentEvent_TeamParticipationTimedOut_EntryFeeRefund  ETournamentEvent = 9
	ETournamentEvent_k_ETournamentEvent_TeamParticipationTimedOut_EntryFeeForfeit ETournamentEvent = 10
	ETournamentEvent_k_ETournamentEvent_TeamParticipationTimedOut_GrantedVictory  ETournamentEvent = 11
)

var ETournamentEvent_name = map[int32]string{
	0:  "k_ETournamentEvent_None",
	1:  "k_ETournamentEvent_TournamentCreated",
	2:  "k_ETournamentEvent_TournamentsMerged",
	3:  "k_ETournamentEvent_GameOutcome",
	4:  "k_ETournamentEvent_TeamGivenBye",
	5:  "k_ETournamentEvent_TournamentCanceledByAdmin",
	6:  "k_ETournamentEvent_TeamAbandoned",
	7:  "k_ETournamentEvent_ScheduledGameStarted",
	8:  "k_ETournamentEvent_Canceled",
	9:  "k_ETournamentEvent_TeamParticipationTimedOut_EntryFeeRefund",
	10: "k_ETournamentEvent_TeamParticipationTimedOut_EntryFeeForfeit",
	11: "k_ETournamentEvent_TeamParticipationTimedOut_GrantedVictory",
}

var ETournamentEvent_value = map[string]int32{
	"k_ETournamentEvent_None":                                      0,
	"k_ETournamentEvent_TournamentCreated":                         1,
	"k_ETournamentEvent_TournamentsMerged":                         2,
	"k_ETournamentEvent_GameOutcome":                               3,
	"k_ETournamentEvent_TeamGivenBye":                              4,
	"k_ETournamentEvent_TournamentCanceledByAdmin":                 5,
	"k_ETournamentEvent_TeamAbandoned":                             6,
	"k_ETournamentEvent_ScheduledGameStarted":                      7,
	"k_ETournamentEvent_Canceled":                                  8,
	"k_ETournamentEvent_TeamParticipationTimedOut_EntryFeeRefund":  9,
	"k_ETournamentEvent_TeamParticipationTimedOut_EntryFeeForfeit": 10,
	"k_ETournamentEvent_TeamParticipationTimedOut_GrantedVictory":  11,
}

func (x ETournamentEvent) Enum() *ETournamentEvent {
	p := new(ETournamentEvent)
	*p = x
	return p
}

func (x ETournamentEvent) String() string {
	return proto.EnumName(ETournamentEvent_name, int32(x))
}

func (x *ETournamentEvent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETournamentEvent_value, data, "ETournamentEvent")
	if err != nil {
		return err
	}
	*x = ETournamentEvent(value)
	return nil
}

func (ETournamentEvent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{0}
}

type CMsgRequestWeekendTourneySchedule struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgRequestWeekendTourneySchedule) Reset()         { *m = CMsgRequestWeekendTourneySchedule{} }
func (m *CMsgRequestWeekendTourneySchedule) String() string { return proto.CompactTextString(m) }
func (*CMsgRequestWeekendTourneySchedule) ProtoMessage()    {}
func (*CMsgRequestWeekendTourneySchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{0}
}

func (m *CMsgRequestWeekendTourneySchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgRequestWeekendTourneySchedule.Unmarshal(m, b)
}
func (m *CMsgRequestWeekendTourneySchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgRequestWeekendTourneySchedule.Marshal(b, m, deterministic)
}
func (m *CMsgRequestWeekendTourneySchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgRequestWeekendTourneySchedule.Merge(m, src)
}
func (m *CMsgRequestWeekendTourneySchedule) XXX_Size() int {
	return xxx_messageInfo_CMsgRequestWeekendTourneySchedule.Size(m)
}
func (m *CMsgRequestWeekendTourneySchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgRequestWeekendTourneySchedule.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgRequestWeekendTourneySchedule proto.InternalMessageInfo

type CMsgWeekendTourneySchedule struct {
	Divisions            []*CMsgWeekendTourneySchedule_Division `protobuf:"bytes,1,rep,name=divisions" json:"divisions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *CMsgWeekendTourneySchedule) Reset()         { *m = CMsgWeekendTourneySchedule{} }
func (m *CMsgWeekendTourneySchedule) String() string { return proto.CompactTextString(m) }
func (*CMsgWeekendTourneySchedule) ProtoMessage()    {}
func (*CMsgWeekendTourneySchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{1}
}

func (m *CMsgWeekendTourneySchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgWeekendTourneySchedule.Unmarshal(m, b)
}
func (m *CMsgWeekendTourneySchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgWeekendTourneySchedule.Marshal(b, m, deterministic)
}
func (m *CMsgWeekendTourneySchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgWeekendTourneySchedule.Merge(m, src)
}
func (m *CMsgWeekendTourneySchedule) XXX_Size() int {
	return xxx_messageInfo_CMsgWeekendTourneySchedule.Size(m)
}
func (m *CMsgWeekendTourneySchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgWeekendTourneySchedule.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgWeekendTourneySchedule proto.InternalMessageInfo

func (m *CMsgWeekendTourneySchedule) GetDivisions() []*CMsgWeekendTourneySchedule_Division {
	if m != nil {
		return m.Divisions
	}
	return nil
}

type CMsgWeekendTourneySchedule_Division struct {
	DivisionCode         *uint32  `protobuf:"varint,1,opt,name=division_code,json=divisionCode" json:"division_code,omitempty"`
	TimeWindowOpen       *uint32  `protobuf:"varint,2,opt,name=time_window_open,json=timeWindowOpen" json:"time_window_open,omitempty"`
	TimeWindowClose      *uint32  `protobuf:"varint,3,opt,name=time_window_close,json=timeWindowClose" json:"time_window_close,omitempty"`
	TimeWindowOpenNext   *uint32  `protobuf:"varint,4,opt,name=time_window_open_next,json=timeWindowOpenNext" json:"time_window_open_next,omitempty"`
	TrophyId             *uint32  `protobuf:"varint,5,opt,name=trophy_id,json=trophyId" json:"trophy_id,omitempty"`
	FreeWeekend          *bool    `protobuf:"varint,6,opt,name=free_weekend,json=freeWeekend" json:"free_weekend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgWeekendTourneySchedule_Division) Reset()         { *m = CMsgWeekendTourneySchedule_Division{} }
func (m *CMsgWeekendTourneySchedule_Division) String() string { return proto.CompactTextString(m) }
func (*CMsgWeekendTourneySchedule_Division) ProtoMessage()    {}
func (*CMsgWeekendTourneySchedule_Division) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{1, 0}
}

func (m *CMsgWeekendTourneySchedule_Division) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgWeekendTourneySchedule_Division.Unmarshal(m, b)
}
func (m *CMsgWeekendTourneySchedule_Division) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgWeekendTourneySchedule_Division.Marshal(b, m, deterministic)
}
func (m *CMsgWeekendTourneySchedule_Division) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgWeekendTourneySchedule_Division.Merge(m, src)
}
func (m *CMsgWeekendTourneySchedule_Division) XXX_Size() int {
	return xxx_messageInfo_CMsgWeekendTourneySchedule_Division.Size(m)
}
func (m *CMsgWeekendTourneySchedule_Division) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgWeekendTourneySchedule_Division.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgWeekendTourneySchedule_Division proto.InternalMessageInfo

func (m *CMsgWeekendTourneySchedule_Division) GetDivisionCode() uint32 {
	if m != nil && m.DivisionCode != nil {
		return *m.DivisionCode
	}
	return 0
}

func (m *CMsgWeekendTourneySchedule_Division) GetTimeWindowOpen() uint32 {
	if m != nil && m.TimeWindowOpen != nil {
		return *m.TimeWindowOpen
	}
	return 0
}

func (m *CMsgWeekendTourneySchedule_Division) GetTimeWindowClose() uint32 {
	if m != nil && m.TimeWindowClose != nil {
		return *m.TimeWindowClose
	}
	return 0
}

func (m *CMsgWeekendTourneySchedule_Division) GetTimeWindowOpenNext() uint32 {
	if m != nil && m.TimeWindowOpenNext != nil {
		return *m.TimeWindowOpenNext
	}
	return 0
}

func (m *CMsgWeekendTourneySchedule_Division) GetTrophyId() uint32 {
	if m != nil && m.TrophyId != nil {
		return *m.TrophyId
	}
	return 0
}

func (m *CMsgWeekendTourneySchedule_Division) GetFreeWeekend() bool {
	if m != nil && m.FreeWeekend != nil {
		return *m.FreeWeekend
	}
	return false
}

type CMsgWeekendTourneyOpts struct {
	Participating        *bool    `protobuf:"varint,1,opt,name=participating" json:"participating,omitempty"`
	DivisionId           *uint32  `protobuf:"varint,2,opt,name=division_id,json=divisionId" json:"division_id,omitempty"`
	Buyin                *uint32  `protobuf:"varint,3,opt,name=buyin" json:"buyin,omitempty"`
	SkillLevel           *uint32  `protobuf:"varint,4,opt,name=skill_level,json=skillLevel" json:"skill_level,omitempty"`
	MatchGroups          *uint32  `protobuf:"varint,5,opt,name=match_groups,json=matchGroups" json:"match_groups,omitempty"`
	TeamId               *uint32  `protobuf:"varint,6,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	PickupTeamName       *string  `protobuf:"bytes,7,opt,name=pickup_team_name,json=pickupTeamName" json:"pickup_team_name,omitempty"`
	PickupTeamLogo       *uint64  `protobuf:"varint,8,opt,name=pickup_team_logo,json=pickupTeamLogo" json:"pickup_team_logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgWeekendTourneyOpts) Reset()         { *m = CMsgWeekendTourneyOpts{} }
func (m *CMsgWeekendTourneyOpts) String() string { return proto.CompactTextString(m) }
func (*CMsgWeekendTourneyOpts) ProtoMessage()    {}
func (*CMsgWeekendTourneyOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{2}
}

func (m *CMsgWeekendTourneyOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgWeekendTourneyOpts.Unmarshal(m, b)
}
func (m *CMsgWeekendTourneyOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgWeekendTourneyOpts.Marshal(b, m, deterministic)
}
func (m *CMsgWeekendTourneyOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgWeekendTourneyOpts.Merge(m, src)
}
func (m *CMsgWeekendTourneyOpts) XXX_Size() int {
	return xxx_messageInfo_CMsgWeekendTourneyOpts.Size(m)
}
func (m *CMsgWeekendTourneyOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgWeekendTourneyOpts.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgWeekendTourneyOpts proto.InternalMessageInfo

func (m *CMsgWeekendTourneyOpts) GetParticipating() bool {
	if m != nil && m.Participating != nil {
		return *m.Participating
	}
	return false
}

func (m *CMsgWeekendTourneyOpts) GetDivisionId() uint32 {
	if m != nil && m.DivisionId != nil {
		return *m.DivisionId
	}
	return 0
}

func (m *CMsgWeekendTourneyOpts) GetBuyin() uint32 {
	if m != nil && m.Buyin != nil {
		return *m.Buyin
	}
	return 0
}

func (m *CMsgWeekendTourneyOpts) GetSkillLevel() uint32 {
	if m != nil && m.SkillLevel != nil {
		return *m.SkillLevel
	}
	return 0
}

func (m *CMsgWeekendTourneyOpts) GetMatchGroups() uint32 {
	if m != nil && m.MatchGroups != nil {
		return *m.MatchGroups
	}
	return 0
}

func (m *CMsgWeekendTourneyOpts) GetTeamId() uint32 {
	if m != nil && m.TeamId != nil {
		return *m.TeamId
	}
	return 0
}

func (m *CMsgWeekendTourneyOpts) GetPickupTeamName() string {
	if m != nil && m.PickupTeamName != nil {
		return *m.PickupTeamName
	}
	return ""
}

func (m *CMsgWeekendTourneyOpts) GetPickupTeamLogo() uint64 {
	if m != nil && m.PickupTeamLogo != nil {
		return *m.PickupTeamLogo
	}
	return 0
}

type CMsgWeekendTourneyLeave struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgWeekendTourneyLeave) Reset()         { *m = CMsgWeekendTourneyLeave{} }
func (m *CMsgWeekendTourneyLeave) String() string { return proto.CompactTextString(m) }
func (*CMsgWeekendTourneyLeave) ProtoMessage()    {}
func (*CMsgWeekendTourneyLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{3}
}

func (m *CMsgWeekendTourneyLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgWeekendTourneyLeave.Unmarshal(m, b)
}
func (m *CMsgWeekendTourneyLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgWeekendTourneyLeave.Marshal(b, m, deterministic)
}
func (m *CMsgWeekendTourneyLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgWeekendTourneyLeave.Merge(m, src)
}
func (m *CMsgWeekendTourneyLeave) XXX_Size() int {
	return xxx_messageInfo_CMsgWeekendTourneyLeave.Size(m)
}
func (m *CMsgWeekendTourneyLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgWeekendTourneyLeave.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgWeekendTourneyLeave proto.InternalMessageInfo

type CMsgDOTATournament struct {
	TournamentId         *uint32                    `protobuf:"varint,1,opt,name=tournament_id,json=tournamentId" json:"tournament_id,omitempty"`
	DivisionId           *uint32                    `protobuf:"varint,2,opt,name=division_id,json=divisionId" json:"division_id,omitempty"`
	ScheduleTime         *uint32                    `protobuf:"varint,3,opt,name=schedule_time,json=scheduleTime" json:"schedule_time,omitempty"`
	SkillLevel           *uint32                    `protobuf:"varint,4,opt,name=skill_level,json=skillLevel" json:"skill_level,omitempty"`
	TournamentTemplate   *ETournamentTemplate       `protobuf:"varint,5,opt,name=tournament_template,json=tournamentTemplate,enum=protocol.ETournamentTemplate,def=0" json:"tournament_template,omitempty"`
	State                *ETournamentState          `protobuf:"varint,6,opt,name=state,enum=protocol.ETournamentState,def=0" json:"state,omitempty"`
	StateSeqNum          *uint32                    `protobuf:"varint,10,opt,name=state_seq_num,json=stateSeqNum" json:"state_seq_num,omitempty"`
	SeasonTrophyId       *uint32                    `protobuf:"varint,11,opt,name=season_trophy_id,json=seasonTrophyId" json:"season_trophy_id,omitempty"`
	Teams                []*CMsgDOTATournament_Team `protobuf:"bytes,7,rep,name=teams" json:"teams,omitempty"`
	Games                []*CMsgDOTATournament_Game `protobuf:"bytes,8,rep,name=games" json:"games,omitempty"`
	Nodes                []*CMsgDOTATournament_Node `protobuf:"bytes,9,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CMsgDOTATournament) Reset()         { *m = CMsgDOTATournament{} }
func (m *CMsgDOTATournament) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTATournament) ProtoMessage()    {}
func (*CMsgDOTATournament) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{4}
}

func (m *CMsgDOTATournament) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTATournament.Unmarshal(m, b)
}
func (m *CMsgDOTATournament) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTATournament.Marshal(b, m, deterministic)
}
func (m *CMsgDOTATournament) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTATournament.Merge(m, src)
}
func (m *CMsgDOTATournament) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTATournament.Size(m)
}
func (m *CMsgDOTATournament) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTATournament.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTATournament proto.InternalMessageInfo

const Default_CMsgDOTATournament_TournamentTemplate ETournamentTemplate = ETournamentTemplate_k_ETournamentTemplate_None
const Default_CMsgDOTATournament_State ETournamentState = ETournamentState_k_ETournamentState_Unknown

func (m *CMsgDOTATournament) GetTournamentId() uint32 {
	if m != nil && m.TournamentId != nil {
		return *m.TournamentId
	}
	return 0
}

func (m *CMsgDOTATournament) GetDivisionId() uint32 {
	if m != nil && m.DivisionId != nil {
		return *m.DivisionId
	}
	return 0
}

func (m *CMsgDOTATournament) GetScheduleTime() uint32 {
	if m != nil && m.ScheduleTime != nil {
		return *m.ScheduleTime
	}
	return 0
}

func (m *CMsgDOTATournament) GetSkillLevel() uint32 {
	if m != nil && m.SkillLevel != nil {
		return *m.SkillLevel
	}
	return 0
}

func (m *CMsgDOTATournament) GetTournamentTemplate() ETournamentTemplate {
	if m != nil && m.TournamentTemplate != nil {
		return *m.TournamentTemplate
	}
	return Default_CMsgDOTATournament_TournamentTemplate
}

func (m *CMsgDOTATournament) GetState() ETournamentState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return Default_CMsgDOTATournament_State
}

func (m *CMsgDOTATournament) GetStateSeqNum() uint32 {
	if m != nil && m.StateSeqNum != nil {
		return *m.StateSeqNum
	}
	return 0
}

func (m *CMsgDOTATournament) GetSeasonTrophyId() uint32 {
	if m != nil && m.SeasonTrophyId != nil {
		return *m.SeasonTrophyId
	}
	return 0
}

func (m *CMsgDOTATournament) GetTeams() []*CMsgDOTATournament_Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *CMsgDOTATournament) GetGames() []*CMsgDOTATournament_Game {
	if m != nil {
		return m.Games
	}
	return nil
}

func (m *CMsgDOTATournament) GetNodes() []*CMsgDOTATournament_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type CMsgDOTATournament_Team struct {
	TeamGid              *uint64  `protobuf:"fixed64,1,opt,name=team_gid,json=teamGid" json:"team_gid,omitempty"`
	NodeOrState          *uint32  `protobuf:"varint,2,opt,name=node_or_state,json=nodeOrState" json:"node_or_state,omitempty"`
	Players              []uint32 `protobuf:"varint,3,rep,packed,name=players" json:"players,omitempty"`
	PlayerBuyin          []uint32 `protobuf:"varint,9,rep,packed,name=player_buyin,json=playerBuyin" json:"player_buyin,omitempty"`
	PlayerSkillLevel     []uint32 `protobuf:"varint,10,rep,packed,name=player_skill_level,json=playerSkillLevel" json:"player_skill_level,omitempty"`
	MatchGroupMask       *uint32  `protobuf:"varint,12,opt,name=match_group_mask,json=matchGroupMask" json:"match_group_mask,omitempty"`
	TeamId               *uint32  `protobuf:"varint,4,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	TeamName             *string  `protobuf:"bytes,5,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	TeamBaseLogo         *uint64  `protobuf:"varint,7,opt,name=team_base_logo,json=teamBaseLogo" json:"team_base_logo,omitempty"`
	TeamUiLogo           *uint64  `protobuf:"varint,8,opt,name=team_ui_logo,json=teamUiLogo" json:"team_ui_logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTATournament_Team) Reset()         { *m = CMsgDOTATournament_Team{} }
func (m *CMsgDOTATournament_Team) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTATournament_Team) ProtoMessage()    {}
func (*CMsgDOTATournament_Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{4, 0}
}

func (m *CMsgDOTATournament_Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTATournament_Team.Unmarshal(m, b)
}
func (m *CMsgDOTATournament_Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTATournament_Team.Marshal(b, m, deterministic)
}
func (m *CMsgDOTATournament_Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTATournament_Team.Merge(m, src)
}
func (m *CMsgDOTATournament_Team) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTATournament_Team.Size(m)
}
func (m *CMsgDOTATournament_Team) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTATournament_Team.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTATournament_Team proto.InternalMessageInfo

func (m *CMsgDOTATournament_Team) GetTeamGid() uint64 {
	if m != nil && m.TeamGid != nil {
		return *m.TeamGid
	}
	return 0
}

func (m *CMsgDOTATournament_Team) GetNodeOrState() uint32 {
	if m != nil && m.NodeOrState != nil {
		return *m.NodeOrState
	}
	return 0
}

func (m *CMsgDOTATournament_Team) GetPlayers() []uint32 {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *CMsgDOTATournament_Team) GetPlayerBuyin() []uint32 {
	if m != nil {
		return m.PlayerBuyin
	}
	return nil
}

func (m *CMsgDOTATournament_Team) GetPlayerSkillLevel() []uint32 {
	if m != nil {
		return m.PlayerSkillLevel
	}
	return nil
}

func (m *CMsgDOTATournament_Team) GetMatchGroupMask() uint32 {
	if m != nil && m.MatchGroupMask != nil {
		return *m.MatchGroupMask
	}
	return 0
}

func (m *CMsgDOTATournament_Team) GetTeamId() uint32 {
	if m != nil && m.TeamId != nil {
		return *m.TeamId
	}
	return 0
}

func (m *CMsgDOTATournament_Team) GetTeamName() string {
	if m != nil && m.TeamName != nil {
		return *m.TeamName
	}
	return ""
}

func (m *CMsgDOTATournament_Team) GetTeamBaseLogo() uint64 {
	if m != nil && m.TeamBaseLogo != nil {
		return *m.TeamBaseLogo
	}
	return 0
}

func (m *CMsgDOTATournament_Team) GetTeamUiLogo() uint64 {
	if m != nil && m.TeamUiLogo != nil {
		return *m.TeamUiLogo
	}
	return 0
}

type CMsgDOTATournament_Game struct {
	NodeIdx              *uint32               `protobuf:"varint,1,opt,name=node_idx,json=nodeIdx" json:"node_idx,omitempty"`
	LobbyId              *uint64               `protobuf:"fixed64,2,opt,name=lobby_id,json=lobbyId" json:"lobby_id,omitempty"`
	MatchId              *uint64               `protobuf:"varint,3,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	TeamAGood            *bool                 `protobuf:"varint,4,opt,name=team_a_good,json=teamAGood" json:"team_a_good,omitempty"`
	State                *ETournamentGameState `protobuf:"varint,5,opt,name=state,enum=protocol.ETournamentGameState,def=0" json:"state,omitempty"`
	StartTime            *uint32               `protobuf:"varint,6,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgDOTATournament_Game) Reset()         { *m = CMsgDOTATournament_Game{} }
func (m *CMsgDOTATournament_Game) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTATournament_Game) ProtoMessage()    {}
func (*CMsgDOTATournament_Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{4, 1}
}

func (m *CMsgDOTATournament_Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTATournament_Game.Unmarshal(m, b)
}
func (m *CMsgDOTATournament_Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTATournament_Game.Marshal(b, m, deterministic)
}
func (m *CMsgDOTATournament_Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTATournament_Game.Merge(m, src)
}
func (m *CMsgDOTATournament_Game) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTATournament_Game.Size(m)
}
func (m *CMsgDOTATournament_Game) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTATournament_Game.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTATournament_Game proto.InternalMessageInfo

const Default_CMsgDOTATournament_Game_State ETournamentGameState = ETournamentGameState_k_ETournamentGameState_Unknown

func (m *CMsgDOTATournament_Game) GetNodeIdx() uint32 {
	if m != nil && m.NodeIdx != nil {
		return *m.NodeIdx
	}
	return 0
}

func (m *CMsgDOTATournament_Game) GetLobbyId() uint64 {
	if m != nil && m.LobbyId != nil {
		return *m.LobbyId
	}
	return 0
}

func (m *CMsgDOTATournament_Game) GetMatchId() uint64 {
	if m != nil && m.MatchId != nil {
		return *m.MatchId
	}
	return 0
}

func (m *CMsgDOTATournament_Game) GetTeamAGood() bool {
	if m != nil && m.TeamAGood != nil {
		return *m.TeamAGood
	}
	return false
}

func (m *CMsgDOTATournament_Game) GetState() ETournamentGameState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return Default_CMsgDOTATournament_Game_State
}

func (m *CMsgDOTATournament_Game) GetStartTime() uint32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

type CMsgDOTATournament_Node struct {
	NodeId               *uint32               `protobuf:"varint,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	TeamIdxA             *uint32               `protobuf:"varint,2,opt,name=team_idx_a,json=teamIdxA" json:"team_idx_a,omitempty"`
	TeamIdxB             *uint32               `protobuf:"varint,3,opt,name=team_idx_b,json=teamIdxB" json:"team_idx_b,omitempty"`
	NodeState            *ETournamentNodeState `protobuf:"varint,4,opt,name=node_state,json=nodeState,enum=protocol.ETournamentNodeState,def=0" json:"node_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgDOTATournament_Node) Reset()         { *m = CMsgDOTATournament_Node{} }
func (m *CMsgDOTATournament_Node) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTATournament_Node) ProtoMessage()    {}
func (*CMsgDOTATournament_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{4, 2}
}

func (m *CMsgDOTATournament_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTATournament_Node.Unmarshal(m, b)
}
func (m *CMsgDOTATournament_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTATournament_Node.Marshal(b, m, deterministic)
}
func (m *CMsgDOTATournament_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTATournament_Node.Merge(m, src)
}
func (m *CMsgDOTATournament_Node) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTATournament_Node.Size(m)
}
func (m *CMsgDOTATournament_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTATournament_Node.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTATournament_Node proto.InternalMessageInfo

const Default_CMsgDOTATournament_Node_NodeState ETournamentNodeState = ETournamentNodeState_k_ETournamentNodeState_Unknown

func (m *CMsgDOTATournament_Node) GetNodeId() uint32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *CMsgDOTATournament_Node) GetTeamIdxA() uint32 {
	if m != nil && m.TeamIdxA != nil {
		return *m.TeamIdxA
	}
	return 0
}

func (m *CMsgDOTATournament_Node) GetTeamIdxB() uint32 {
	if m != nil && m.TeamIdxB != nil {
		return *m.TeamIdxB
	}
	return 0
}

func (m *CMsgDOTATournament_Node) GetNodeState() ETournamentNodeState {
	if m != nil && m.NodeState != nil {
		return *m.NodeState
	}
	return Default_CMsgDOTATournament_Node_NodeState
}

type CMsgDOTATournamentStateChange struct {
	NewTournamentId      *uint32                                     `protobuf:"varint,1,opt,name=new_tournament_id,json=newTournamentId" json:"new_tournament_id,omitempty"`
	Event                *ETournamentEvent                           `protobuf:"varint,2,opt,name=event,enum=protocol.ETournamentEvent,def=0" json:"event,omitempty"`
	NewTournamentState   *ETournamentState                           `protobuf:"varint,3,opt,name=new_tournament_state,json=newTournamentState,enum=protocol.ETournamentState,def=0" json:"new_tournament_state,omitempty"`
	GameChanges          []*CMsgDOTATournamentStateChange_GameChange `protobuf:"bytes,4,rep,name=game_changes,json=gameChanges" json:"game_changes,omitempty"`
	TeamChanges          []*CMsgDOTATournamentStateChange_TeamChange `protobuf:"bytes,5,rep,name=team_changes,json=teamChanges" json:"team_changes,omitempty"`
	MergedTournamentIds  []uint32                                    `protobuf:"varint,6,rep,packed,name=merged_tournament_ids,json=mergedTournamentIds" json:"merged_tournament_ids,omitempty"`
	StateSeqNum          *uint32                                     `protobuf:"varint,7,opt,name=state_seq_num,json=stateSeqNum" json:"state_seq_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *CMsgDOTATournamentStateChange) Reset()         { *m = CMsgDOTATournamentStateChange{} }
func (m *CMsgDOTATournamentStateChange) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTATournamentStateChange) ProtoMessage()    {}
func (*CMsgDOTATournamentStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{5}
}

func (m *CMsgDOTATournamentStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTATournamentStateChange.Unmarshal(m, b)
}
func (m *CMsgDOTATournamentStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTATournamentStateChange.Marshal(b, m, deterministic)
}
func (m *CMsgDOTATournamentStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTATournamentStateChange.Merge(m, src)
}
func (m *CMsgDOTATournamentStateChange) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTATournamentStateChange.Size(m)
}
func (m *CMsgDOTATournamentStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTATournamentStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTATournamentStateChange proto.InternalMessageInfo

const Default_CMsgDOTATournamentStateChange_Event ETournamentEvent = ETournamentEvent_k_ETournamentEvent_None
const Default_CMsgDOTATournamentStateChange_NewTournamentState ETournamentState = ETournamentState_k_ETournamentState_Unknown

func (m *CMsgDOTATournamentStateChange) GetNewTournamentId() uint32 {
	if m != nil && m.NewTournamentId != nil {
		return *m.NewTournamentId
	}
	return 0
}

func (m *CMsgDOTATournamentStateChange) GetEvent() ETournamentEvent {
	if m != nil && m.Event != nil {
		return *m.Event
	}
	return Default_CMsgDOTATournamentStateChange_Event
}

func (m *CMsgDOTATournamentStateChange) GetNewTournamentState() ETournamentState {
	if m != nil && m.NewTournamentState != nil {
		return *m.NewTournamentState
	}
	return Default_CMsgDOTATournamentStateChange_NewTournamentState
}

func (m *CMsgDOTATournamentStateChange) GetGameChanges() []*CMsgDOTATournamentStateChange_GameChange {
	if m != nil {
		return m.GameChanges
	}
	return nil
}

func (m *CMsgDOTATournamentStateChange) GetTeamChanges() []*CMsgDOTATournamentStateChange_TeamChange {
	if m != nil {
		return m.TeamChanges
	}
	return nil
}

func (m *CMsgDOTATournamentStateChange) GetMergedTournamentIds() []uint32 {
	if m != nil {
		return m.MergedTournamentIds
	}
	return nil
}

func (m *CMsgDOTATournamentStateChange) GetStateSeqNum() uint32 {
	if m != nil && m.StateSeqNum != nil {
		return *m.StateSeqNum
	}
	return 0
}

type CMsgDOTATournamentStateChange_GameChange struct {
	MatchId              *uint64               `protobuf:"varint,1,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	NewState             *ETournamentGameState `protobuf:"varint,2,opt,name=new_state,json=newState,enum=protocol.ETournamentGameState,def=0" json:"new_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CMsgDOTATournamentStateChange_GameChange) Reset() {
	*m = CMsgDOTATournamentStateChange_GameChange{}
}
func (m *CMsgDOTATournamentStateChange_GameChange) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTATournamentStateChange_GameChange) ProtoMessage()    {}
func (*CMsgDOTATournamentStateChange_GameChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{5, 0}
}

func (m *CMsgDOTATournamentStateChange_GameChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTATournamentStateChange_GameChange.Unmarshal(m, b)
}
func (m *CMsgDOTATournamentStateChange_GameChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTATournamentStateChange_GameChange.Marshal(b, m, deterministic)
}
func (m *CMsgDOTATournamentStateChange_GameChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTATournamentStateChange_GameChange.Merge(m, src)
}
func (m *CMsgDOTATournamentStateChange_GameChange) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTATournamentStateChange_GameChange.Size(m)
}
func (m *CMsgDOTATournamentStateChange_GameChange) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTATournamentStateChange_GameChange.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTATournamentStateChange_GameChange proto.InternalMessageInfo

const Default_CMsgDOTATournamentStateChange_GameChange_NewState ETournamentGameState = ETournamentGameState_k_ETournamentGameState_Unknown

func (m *CMsgDOTATournamentStateChange_GameChange) GetMatchId() uint64 {
	if m != nil && m.MatchId != nil {
		return *m.MatchId
	}
	return 0
}

func (m *CMsgDOTATournamentStateChange_GameChange) GetNewState() ETournamentGameState {
	if m != nil && m.NewState != nil {
		return *m.NewState
	}
	return Default_CMsgDOTATournamentStateChange_GameChange_NewState
}

type CMsgDOTATournamentStateChange_TeamChange struct {
	TeamGid              *uint64  `protobuf:"varint,1,opt,name=team_gid,json=teamGid" json:"team_gid,omitempty"`
	NewNodeOrState       *uint32  `protobuf:"varint,2,opt,name=new_node_or_state,json=newNodeOrState" json:"new_node_or_state,omitempty"`
	OldNodeOrState       *uint32  `protobuf:"varint,3,opt,name=old_node_or_state,json=oldNodeOrState" json:"old_node_or_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTATournamentStateChange_TeamChange) Reset() {
	*m = CMsgDOTATournamentStateChange_TeamChange{}
}
func (m *CMsgDOTATournamentStateChange_TeamChange) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTATournamentStateChange_TeamChange) ProtoMessage()    {}
func (*CMsgDOTATournamentStateChange_TeamChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{5, 1}
}

func (m *CMsgDOTATournamentStateChange_TeamChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTATournamentStateChange_TeamChange.Unmarshal(m, b)
}
func (m *CMsgDOTATournamentStateChange_TeamChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTATournamentStateChange_TeamChange.Marshal(b, m, deterministic)
}
func (m *CMsgDOTATournamentStateChange_TeamChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTATournamentStateChange_TeamChange.Merge(m, src)
}
func (m *CMsgDOTATournamentStateChange_TeamChange) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTATournamentStateChange_TeamChange.Size(m)
}
func (m *CMsgDOTATournamentStateChange_TeamChange) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTATournamentStateChange_TeamChange.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTATournamentStateChange_TeamChange proto.InternalMessageInfo

func (m *CMsgDOTATournamentStateChange_TeamChange) GetTeamGid() uint64 {
	if m != nil && m.TeamGid != nil {
		return *m.TeamGid
	}
	return 0
}

func (m *CMsgDOTATournamentStateChange_TeamChange) GetNewNodeOrState() uint32 {
	if m != nil && m.NewNodeOrState != nil {
		return *m.NewNodeOrState
	}
	return 0
}

func (m *CMsgDOTATournamentStateChange_TeamChange) GetOldNodeOrState() uint32 {
	if m != nil && m.OldNodeOrState != nil {
		return *m.OldNodeOrState
	}
	return 0
}

type CMsgDOTAWeekendTourneyPlayerSkillLevelStats struct {
	SkillLevel           *uint32  `protobuf:"varint,1,opt,name=skill_level,json=skillLevel" json:"skill_level,omitempty"`
	TimesWon_0           *uint32  `protobuf:"varint,2,opt,name=times_won_0,json=timesWon0" json:"times_won_0,omitempty"`
	TimesWon_1           *uint32  `protobuf:"varint,3,opt,name=times_won_1,json=timesWon1" json:"times_won_1,omitempty"`
	TimesWon_2           *uint32  `protobuf:"varint,4,opt,name=times_won_2,json=timesWon2" json:"times_won_2,omitempty"`
	TimesWon_3           *uint32  `protobuf:"varint,5,opt,name=times_won_3,json=timesWon3" json:"times_won_3,omitempty"`
	TimesByeAndLost      *uint32  `protobuf:"varint,6,opt,name=times_bye_and_lost,json=timesByeAndLost" json:"times_bye_and_lost,omitempty"`
	TimesByeAndWon       *uint32  `protobuf:"varint,7,opt,name=times_bye_and_won,json=timesByeAndWon" json:"times_bye_and_won,omitempty"`
	TimesUnusualChamp    *uint32  `protobuf:"varint,10,opt,name=times_unusual_champ,json=timesUnusualChamp" json:"times_unusual_champ,omitempty"`
	TotalGamesWon        *uint32  `protobuf:"varint,8,opt,name=total_games_won,json=totalGamesWon" json:"total_games_won,omitempty"`
	Score                *uint32  `protobuf:"varint,9,opt,name=score" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) Reset() {
	*m = CMsgDOTAWeekendTourneyPlayerSkillLevelStats{}
}
func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAWeekendTourneyPlayerSkillLevelStats) ProtoMessage() {}
func (*CMsgDOTAWeekendTourneyPlayerSkillLevelStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{6}
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerSkillLevelStats.Unmarshal(m, b)
}
func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerSkillLevelStats.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerSkillLevelStats.Merge(m, src)
}
func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerSkillLevelStats.Size(m)
}
func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerSkillLevelStats.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerSkillLevelStats proto.InternalMessageInfo

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetSkillLevel() uint32 {
	if m != nil && m.SkillLevel != nil {
		return *m.SkillLevel
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetTimesWon_0() uint32 {
	if m != nil && m.TimesWon_0 != nil {
		return *m.TimesWon_0
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetTimesWon_1() uint32 {
	if m != nil && m.TimesWon_1 != nil {
		return *m.TimesWon_1
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetTimesWon_2() uint32 {
	if m != nil && m.TimesWon_2 != nil {
		return *m.TimesWon_2
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetTimesWon_3() uint32 {
	if m != nil && m.TimesWon_3 != nil {
		return *m.TimesWon_3
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetTimesByeAndLost() uint32 {
	if m != nil && m.TimesByeAndLost != nil {
		return *m.TimesByeAndLost
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetTimesByeAndWon() uint32 {
	if m != nil && m.TimesByeAndWon != nil {
		return *m.TimesByeAndWon
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetTimesUnusualChamp() uint32 {
	if m != nil && m.TimesUnusualChamp != nil {
		return *m.TimesUnusualChamp
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetTotalGamesWon() uint32 {
	if m != nil && m.TotalGamesWon != nil {
		return *m.TotalGamesWon
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerSkillLevelStats) GetScore() uint32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type CMsgDOTAWeekendTourneyPlayerStats struct {
	AccountId            *uint32                                        `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	SeasonTrophyId       *uint32                                        `protobuf:"varint,2,opt,name=season_trophy_id,json=seasonTrophyId" json:"season_trophy_id,omitempty"`
	SkillLevels          []*CMsgDOTAWeekendTourneyPlayerSkillLevelStats `protobuf:"bytes,3,rep,name=skill_levels,json=skillLevels" json:"skill_levels,omitempty"`
	CurrentTier          *uint32                                        `protobuf:"varint,4,opt,name=current_tier,json=currentTier" json:"current_tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *CMsgDOTAWeekendTourneyPlayerStats) Reset()         { *m = CMsgDOTAWeekendTourneyPlayerStats{} }
func (m *CMsgDOTAWeekendTourneyPlayerStats) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAWeekendTourneyPlayerStats) ProtoMessage()    {}
func (*CMsgDOTAWeekendTourneyPlayerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{7}
}

func (m *CMsgDOTAWeekendTourneyPlayerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStats.Unmarshal(m, b)
}
func (m *CMsgDOTAWeekendTourneyPlayerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStats.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAWeekendTourneyPlayerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStats.Merge(m, src)
}
func (m *CMsgDOTAWeekendTourneyPlayerStats) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStats.Size(m)
}
func (m *CMsgDOTAWeekendTourneyPlayerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStats.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStats proto.InternalMessageInfo

func (m *CMsgDOTAWeekendTourneyPlayerStats) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerStats) GetSeasonTrophyId() uint32 {
	if m != nil && m.SeasonTrophyId != nil {
		return *m.SeasonTrophyId
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerStats) GetSkillLevels() []*CMsgDOTAWeekendTourneyPlayerSkillLevelStats {
	if m != nil {
		return m.SkillLevels
	}
	return nil
}

func (m *CMsgDOTAWeekendTourneyPlayerStats) GetCurrentTier() uint32 {
	if m != nil && m.CurrentTier != nil {
		return *m.CurrentTier
	}
	return 0
}

type CMsgDOTAWeekendTourneyPlayerStatsRequest struct {
	AccountId            *uint32  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	SeasonTrophyId       *uint32  `protobuf:"varint,2,opt,name=season_trophy_id,json=seasonTrophyId" json:"season_trophy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) Reset() {
	*m = CMsgDOTAWeekendTourneyPlayerStatsRequest{}
}
func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAWeekendTourneyPlayerStatsRequest) ProtoMessage()    {}
func (*CMsgDOTAWeekendTourneyPlayerStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{8}
}

func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStatsRequest.Unmarshal(m, b)
}
func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStatsRequest.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStatsRequest.Merge(m, src)
}
func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStatsRequest.Size(m)
}
func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerStatsRequest proto.InternalMessageInfo

func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerStatsRequest) GetSeasonTrophyId() uint32 {
	if m != nil && m.SeasonTrophyId != nil {
		return *m.SeasonTrophyId
	}
	return 0
}

type CMsgDOTAWeekendTourneyPlayerHistory struct {
	AccountId            *uint32                                           `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Tournaments          []*CMsgDOTAWeekendTourneyPlayerHistory_Tournament `protobuf:"bytes,3,rep,name=tournaments" json:"tournaments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory) Reset()         { *m = CMsgDOTAWeekendTourneyPlayerHistory{} }
func (m *CMsgDOTAWeekendTourneyPlayerHistory) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAWeekendTourneyPlayerHistory) ProtoMessage()    {}
func (*CMsgDOTAWeekendTourneyPlayerHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{9}
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory.Unmarshal(m, b)
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory.Merge(m, src)
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory.Size(m)
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory proto.InternalMessageInfo

func (m *CMsgDOTAWeekendTourneyPlayerHistory) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory) GetTournaments() []*CMsgDOTAWeekendTourneyPlayerHistory_Tournament {
	if m != nil {
		return m.Tournaments
	}
	return nil
}

type CMsgDOTAWeekendTourneyPlayerHistory_Tournament struct {
	TournamentId         *uint32  `protobuf:"varint,1,opt,name=tournament_id,json=tournamentId" json:"tournament_id,omitempty"`
	StartTime            *uint32  `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	TournamentTier       *uint32  `protobuf:"varint,3,opt,name=tournament_tier,json=tournamentTier" json:"tournament_tier,omitempty"`
	TeamId               *uint32  `protobuf:"varint,4,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	TeamDate             *uint32  `protobuf:"varint,5,opt,name=team_date,json=teamDate" json:"team_date,omitempty"`
	TeamResult           *uint32  `protobuf:"varint,6,opt,name=team_result,json=teamResult" json:"team_result,omitempty"`
	AccountId            []uint32 `protobuf:"varint,7,rep,name=account_id,json=accountId" json:"account_id,omitempty"`
	TeamName             *string  `protobuf:"bytes,8,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	SeasonTrophyId       *uint32  `protobuf:"varint,9,opt,name=season_trophy_id,json=seasonTrophyId" json:"season_trophy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) Reset() {
	*m = CMsgDOTAWeekendTourneyPlayerHistory_Tournament{}
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAWeekendTourneyPlayerHistory_Tournament) ProtoMessage() {}
func (*CMsgDOTAWeekendTourneyPlayerHistory_Tournament) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{9, 0}
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory_Tournament.Unmarshal(m, b)
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory_Tournament.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory_Tournament.Merge(m, src)
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory_Tournament.Size(m)
}
func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory_Tournament.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAWeekendTourneyPlayerHistory_Tournament proto.InternalMessageInfo

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetTournamentId() uint32 {
	if m != nil && m.TournamentId != nil {
		return *m.TournamentId
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetStartTime() uint32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetTournamentTier() uint32 {
	if m != nil && m.TournamentTier != nil {
		return *m.TournamentTier
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetTeamId() uint32 {
	if m != nil && m.TeamId != nil {
		return *m.TeamId
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetTeamDate() uint32 {
	if m != nil && m.TeamDate != nil {
		return *m.TeamDate
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetTeamResult() uint32 {
	if m != nil && m.TeamResult != nil {
		return *m.TeamResult
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetAccountId() []uint32 {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetTeamName() string {
	if m != nil && m.TeamName != nil {
		return *m.TeamName
	}
	return ""
}

func (m *CMsgDOTAWeekendTourneyPlayerHistory_Tournament) GetSeasonTrophyId() uint32 {
	if m != nil && m.SeasonTrophyId != nil {
		return *m.SeasonTrophyId
	}
	return 0
}

type CMsgDOTAWeekendTourneyParticipationDetails struct {
	Divisions            []*CMsgDOTAWeekendTourneyParticipationDetails_Division `protobuf:"bytes,1,rep,name=divisions" json:"divisions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails) Reset() {
	*m = CMsgDOTAWeekendTourneyParticipationDetails{}
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAWeekendTourneyParticipationDetails) ProtoMessage() {}
func (*CMsgDOTAWeekendTourneyParticipationDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{10}
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails.Unmarshal(m, b)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails.Merge(m, src)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails.Size(m)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails proto.InternalMessageInfo

func (m *CMsgDOTAWeekendTourneyParticipationDetails) GetDivisions() []*CMsgDOTAWeekendTourneyParticipationDetails_Division {
	if m != nil {
		return m.Divisions
	}
	return nil
}

type CMsgDOTAWeekendTourneyParticipationDetails_Tier struct {
	Tier                 *uint32  `protobuf:"varint,1,opt,name=tier" json:"tier,omitempty"`
	Players              *uint32  `protobuf:"varint,2,opt,name=players" json:"players,omitempty"`
	Teams                *uint32  `protobuf:"varint,3,opt,name=teams" json:"teams,omitempty"`
	WinningTeams         *uint32  `protobuf:"varint,4,opt,name=winning_teams,json=winningTeams" json:"winning_teams,omitempty"`
	PlayersStreak_2      *uint32  `protobuf:"varint,5,opt,name=players_streak_2,json=playersStreak2" json:"players_streak_2,omitempty"`
	PlayersStreak_3      *uint32  `protobuf:"varint,6,opt,name=players_streak_3,json=playersStreak3" json:"players_streak_3,omitempty"`
	PlayersStreak_4      *uint32  `protobuf:"varint,7,opt,name=players_streak_4,json=playersStreak4" json:"players_streak_4,omitempty"`
	PlayersStreak_5      *uint32  `protobuf:"varint,8,opt,name=players_streak_5,json=playersStreak5" json:"players_streak_5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) Reset() {
	*m = CMsgDOTAWeekendTourneyParticipationDetails_Tier{}
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAWeekendTourneyParticipationDetails_Tier) ProtoMessage() {}
func (*CMsgDOTAWeekendTourneyParticipationDetails_Tier) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{10, 0}
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Tier.Unmarshal(m, b)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Tier.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Tier.Merge(m, src)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Tier.Size(m)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Tier.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Tier proto.InternalMessageInfo

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) GetTier() uint32 {
	if m != nil && m.Tier != nil {
		return *m.Tier
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) GetPlayers() uint32 {
	if m != nil && m.Players != nil {
		return *m.Players
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) GetTeams() uint32 {
	if m != nil && m.Teams != nil {
		return *m.Teams
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) GetWinningTeams() uint32 {
	if m != nil && m.WinningTeams != nil {
		return *m.WinningTeams
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) GetPlayersStreak_2() uint32 {
	if m != nil && m.PlayersStreak_2 != nil {
		return *m.PlayersStreak_2
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) GetPlayersStreak_3() uint32 {
	if m != nil && m.PlayersStreak_3 != nil {
		return *m.PlayersStreak_3
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) GetPlayersStreak_4() uint32 {
	if m != nil && m.PlayersStreak_4 != nil {
		return *m.PlayersStreak_4
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Tier) GetPlayersStreak_5() uint32 {
	if m != nil && m.PlayersStreak_5 != nil {
		return *m.PlayersStreak_5
	}
	return 0
}

type CMsgDOTAWeekendTourneyParticipationDetails_Division struct {
	DivisionId           *uint32                                            `protobuf:"varint,1,opt,name=division_id,json=divisionId" json:"division_id,omitempty"`
	ScheduleTime         *uint32                                            `protobuf:"varint,2,opt,name=schedule_time,json=scheduleTime" json:"schedule_time,omitempty"`
	Tiers                []*CMsgDOTAWeekendTourneyParticipationDetails_Tier `protobuf:"bytes,3,rep,name=tiers" json:"tiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) Reset() {
	*m = CMsgDOTAWeekendTourneyParticipationDetails_Division{}
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAWeekendTourneyParticipationDetails_Division) ProtoMessage() {}
func (*CMsgDOTAWeekendTourneyParticipationDetails_Division) Descriptor() ([]byte, []int) {
	return fileDescriptor_b078246a3c3a185c, []int{10, 1}
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Division.Unmarshal(m, b)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Division.Marshal(b, m, deterministic)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Division.Merge(m, src)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) XXX_Size() int {
	return xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Division.Size(m)
}
func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Division.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgDOTAWeekendTourneyParticipationDetails_Division proto.InternalMessageInfo

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) GetDivisionId() uint32 {
	if m != nil && m.DivisionId != nil {
		return *m.DivisionId
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) GetScheduleTime() uint32 {
	if m != nil && m.ScheduleTime != nil {
		return *m.ScheduleTime
	}
	return 0
}

func (m *CMsgDOTAWeekendTourneyParticipationDetails_Division) GetTiers() []*CMsgDOTAWeekendTourneyParticipationDetails_Tier {
	if m != nil {
		return m.Tiers
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.ETournamentEvent", ETournamentEvent_name, ETournamentEvent_value)
	proto.RegisterType((*CMsgRequestWeekendTourneySchedule)(nil), "protocol.CMsgRequestWeekendTourneySchedule")
	proto.RegisterType((*CMsgWeekendTourneySchedule)(nil), "protocol.CMsgWeekendTourneySchedule")
	proto.RegisterType((*CMsgWeekendTourneySchedule_Division)(nil), "protocol.CMsgWeekendTourneySchedule.Division")
	proto.RegisterType((*CMsgWeekendTourneyOpts)(nil), "protocol.CMsgWeekendTourneyOpts")
	proto.RegisterType((*CMsgWeekendTourneyLeave)(nil), "protocol.CMsgWeekendTourneyLeave")
	proto.RegisterType((*CMsgDOTATournament)(nil), "protocol.CMsgDOTATournament")
	proto.RegisterType((*CMsgDOTATournament_Team)(nil), "protocol.CMsgDOTATournament.Team")
	proto.RegisterType((*CMsgDOTATournament_Game)(nil), "protocol.CMsgDOTATournament.Game")
	proto.RegisterType((*CMsgDOTATournament_Node)(nil), "protocol.CMsgDOTATournament.Node")
	proto.RegisterType((*CMsgDOTATournamentStateChange)(nil), "protocol.CMsgDOTATournamentStateChange")
	proto.RegisterType((*CMsgDOTATournamentStateChange_GameChange)(nil), "protocol.CMsgDOTATournamentStateChange.GameChange")
	proto.RegisterType((*CMsgDOTATournamentStateChange_TeamChange)(nil), "protocol.CMsgDOTATournamentStateChange.TeamChange")
	proto.RegisterType((*CMsgDOTAWeekendTourneyPlayerSkillLevelStats)(nil), "protocol.CMsgDOTAWeekendTourneyPlayerSkillLevelStats")
	proto.RegisterType((*CMsgDOTAWeekendTourneyPlayerStats)(nil), "protocol.CMsgDOTAWeekendTourneyPlayerStats")
	proto.RegisterType((*CMsgDOTAWeekendTourneyPlayerStatsRequest)(nil), "protocol.CMsgDOTAWeekendTourneyPlayerStatsRequest")
	proto.RegisterType((*CMsgDOTAWeekendTourneyPlayerHistory)(nil), "protocol.CMsgDOTAWeekendTourneyPlayerHistory")
	proto.RegisterType((*CMsgDOTAWeekendTourneyPlayerHistory_Tournament)(nil), "protocol.CMsgDOTAWeekendTourneyPlayerHistory.Tournament")
	proto.RegisterType((*CMsgDOTAWeekendTourneyParticipationDetails)(nil), "protocol.CMsgDOTAWeekendTourneyParticipationDetails")
	proto.RegisterType((*CMsgDOTAWeekendTourneyParticipationDetails_Tier)(nil), "protocol.CMsgDOTAWeekendTourneyParticipationDetails.Tier")
	proto.RegisterType((*CMsgDOTAWeekendTourneyParticipationDetails_Division)(nil), "protocol.CMsgDOTAWeekendTourneyParticipationDetails.Division")
}

func init() {
	proto.RegisterFile("dota_gcmessages_client_tournament.proto", fileDescriptor_b078246a3c3a185c)
}

var fileDescriptor_b078246a3c3a185c = []byte{
	// 1896 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0xdb, 0xc8,
	0x15, 0x5e, 0xc9, 0xfa, 0x3d, 0xb2, 0x1d, 0xed, 0x24, 0xdb, 0x70, 0x95, 0x4d, 0xe2, 0xc8, 0x69,
	0xa3, 0x4d, 0x5a, 0x23, 0x71, 0x36, 0xfd, 0xd9, 0xb6, 0x68, 0x6d, 0x27, 0xeb, 0x35, 0xea, 0xd8,
	0x05, 0xad, 0x34, 0x45, 0x8b, 0x82, 0xa0, 0x35, 0x27, 0x32, 0x6b, 0x72, 0x46, 0xe1, 0x0c, 0x2d,
	0xeb, 0xa2, 0x40, 0x2f, 0xfa, 0x00, 0xbd, 0x28, 0xd0, 0xeb, 0xde, 0xf4, 0x11, 0xf6, 0xa2, 0x2f,
	0xd0, 0x67, 0xe8, 0xfd, 0xa2, 0x40, 0x81, 0x3e, 0x40, 0x2f, 0x8b, 0xf9, 0xa1, 0x28, 0x4a, 0x74,
	0x9c, 0xec, 0xee, 0x95, 0xc8, 0xef, 0x7c, 0x3c, 0x9c, 0x39, 0x3f, 0x1f, 0xcf, 0x08, 0xee, 0x51,
	0x2e, 0x7d, 0x6f, 0x38, 0x88, 0x50, 0x08, 0x7f, 0x88, 0xc2, 0x1b, 0x84, 0x01, 0x32, 0xe9, 0x49,
	0x9e, 0xc4, 0xcc, 0x8f, 0x90, 0xc9, 0x8d, 0x51, 0xcc, 0x25, 0x27, 0x0d, 0xfd, 0x33, 0xe0, 0x61,
	0xe7, 0xba, 0x7e, 0xc4, 0xf2, 0x90, 0x25, 0x91, 0x30, 0x94, 0xee, 0x3a, 0xdc, 0xd9, 0x79, 0x2e,
	0x86, 0x2e, 0xbe, 0x4e, 0x50, 0xc8, 0x97, 0x88, 0xa7, 0xc8, 0x68, 0x5f, 0x39, 0xc2, 0xc9, 0xd1,
	0xe0, 0x04, 0x69, 0x12, 0x62, 0xf7, 0xcb, 0x32, 0x74, 0x14, 0xab, 0xd8, 0x4c, 0x7e, 0x01, 0x4d,
	0x1a, 0x9c, 0x05, 0x22, 0xe0, 0x4c, 0x38, 0xa5, 0xb5, 0xa5, 0x5e, 0x6b, 0xf3, 0x7b, 0x1b, 0xe9,
	0xab, 0x37, 0x2e, 0x7e, 0x70, 0xe3, 0xa9, 0x7d, 0xca, 0xcd, 0x9e, 0xef, 0xfc, 0xaf, 0x04, 0x8d,
	0x14, 0x27, 0xeb, 0xb0, 0x92, 0x5a, 0xbc, 0x01, 0xa7, 0xe8, 0x94, 0xd6, 0x4a, 0xbd, 0x15, 0x77,
	0x39, 0x05, 0x77, 0x38, 0x45, 0xd2, 0x83, 0xb6, 0x0c, 0x22, 0xf4, 0xc6, 0x01, 0xa3, 0x7c, 0xec,
	0xf1, 0x11, 0x32, 0xa7, 0xac, 0x79, 0xab, 0x0a, 0x7f, 0xa9, 0xe1, 0xc3, 0x11, 0x32, 0x72, 0x1f,
	0xde, 0x9f, 0x65, 0x0e, 0x42, 0x2e, 0xd0, 0x59, 0xd2, 0xd4, 0x2b, 0x19, 0x75, 0x47, 0xc1, 0xe4,
	0x11, 0x7c, 0x30, 0xef, 0xd5, 0x63, 0x78, 0x2e, 0x9d, 0x8a, 0xe6, 0x93, 0xbc, 0xeb, 0x03, 0x3c,
	0x97, 0xe4, 0x06, 0x34, 0x65, 0xcc, 0x47, 0x27, 0x13, 0x2f, 0xa0, 0x4e, 0x55, 0xd3, 0x1a, 0x06,
	0xd8, 0xa3, 0xe4, 0x0e, 0x2c, 0xbf, 0x8a, 0x11, 0xbd, 0xb1, 0x09, 0x85, 0x53, 0x5b, 0x2b, 0xf5,
	0x1a, 0x6e, 0x4b, 0x61, 0x36, 0x3a, 0xdd, 0xbf, 0x97, 0xe1, 0x5b, 0x8b, 0xd1, 0x3a, 0x1c, 0x49,
	0x41, 0xee, 0xc2, 0xca, 0xc8, 0x8f, 0x65, 0x30, 0x08, 0x46, 0xbe, 0x0c, 0xd8, 0x50, 0x07, 0xa2,
	0xe1, 0xe6, 0x41, 0x72, 0x1b, 0x5a, 0xd3, 0x70, 0x05, 0xd4, 0x06, 0x01, 0x52, 0x68, 0x8f, 0x92,
	0x6b, 0x50, 0x3d, 0x4e, 0x26, 0x01, 0xb3, 0x9b, 0x36, 0x37, 0xea, 0x31, 0x71, 0x1a, 0x84, 0xa1,
	0x17, 0xe2, 0x19, 0x86, 0x76, 0x83, 0xa0, 0xa1, 0x7d, 0x85, 0xa8, 0xb5, 0x47, 0xbe, 0x1c, 0x9c,
	0x78, 0xc3, 0x98, 0x27, 0x23, 0x61, 0xf7, 0xd6, 0xd2, 0xd8, 0xae, 0x86, 0xc8, 0x75, 0xa8, 0x4b,
	0xf4, 0x23, 0xf5, 0xda, 0x9a, 0xb6, 0xd6, 0xd4, 0xed, 0x1e, 0x55, 0xd9, 0x19, 0x05, 0x83, 0xd3,
	0x64, 0xe4, 0x69, 0xbb, 0xaa, 0x4f, 0xa7, 0xbe, 0x56, 0xea, 0x35, 0xdd, 0x55, 0x83, 0xf7, 0xd1,
	0x8f, 0x0e, 0xfc, 0x08, 0xe7, 0x99, 0x21, 0x1f, 0x72, 0xa7, 0xb1, 0x56, 0xea, 0x55, 0x66, 0x99,
	0xfb, 0x7c, 0xc8, 0xbb, 0x1f, 0xc2, 0xf5, 0xc5, 0x38, 0xed, 0xa3, 0x7f, 0x86, 0xdd, 0x7f, 0x03,
	0x10, 0x65, 0x7b, 0x7a, 0xd8, 0xdf, 0xea, 0x4f, 0xfb, 0x41, 0x15, 0x52, 0xd6, 0x1d, 0x6a, 0x91,
	0xb6, 0x90, 0x32, 0x70, 0x8f, 0x5e, 0x1e, 0xbe, 0x75, 0x58, 0x11, 0xb6, 0x76, 0x3d, 0x95, 0x7f,
	0x1b, 0xc6, 0xe5, 0x14, 0xec, 0x07, 0x11, 0x5e, 0x1e, 0xcd, 0xdf, 0xc3, 0xd5, 0x99, 0xb5, 0x48,
	0x8c, 0x46, 0xa1, 0x2f, 0x51, 0x07, 0x75, 0x75, 0xf3, 0x66, 0xd6, 0x38, 0xcf, 0xb2, 0xf5, 0xf7,
	0x2d, 0xe9, 0xd3, 0xce, 0xa9, 0x57, 0x00, 0x7b, 0x07, 0x9c, 0xa1, 0x4b, 0xe4, 0x82, 0x81, 0xec,
	0x43, 0x55, 0x48, 0xe5, 0xbd, 0xa6, 0xbd, 0x77, 0x0a, 0xbd, 0x1f, 0xc9, 0x45, 0xd7, 0x1a, 0xf3,
	0x5e, 0xb0, 0x53, 0xc6, 0xc7, 0xcc, 0x35, 0x4e, 0x48, 0x17, 0x56, 0xf4, 0x85, 0x27, 0xf0, 0xb5,
	0xc7, 0x92, 0xc8, 0x01, 0x53, 0x08, 0x1a, 0x3c, 0xc2, 0xd7, 0x07, 0x49, 0xa4, 0xb2, 0x28, 0xd0,
	0x17, 0x9c, 0x79, 0x59, 0x2f, 0xb4, 0x4c, 0x37, 0x1a, 0xbc, 0x9f, 0x76, 0xc4, 0x0f, 0xa0, 0xaa,
	0x12, 0x2d, 0x9c, 0xba, 0x96, 0x8c, 0x3b, 0x79, 0xc9, 0xc8, 0x27, 0x70, 0x43, 0xe5, 0xde, 0x35,
	0x7c, 0xf5, 0xe0, 0xd0, 0x8f, 0x50, 0x38, 0x8d, 0xb7, 0x78, 0x70, 0xd7, 0x8f, 0xd0, 0x35, 0x7c,
	0xf5, 0x20, 0xe3, 0x14, 0x85, 0xd3, 0x7c, 0x8b, 0x07, 0x0f, 0x38, 0x45, 0xd7, 0xf0, 0x3b, 0x5f,
	0x96, 0xa1, 0xa2, 0x56, 0x40, 0x3e, 0x84, 0x86, 0x2e, 0xce, 0xa1, 0x2d, 0xa1, 0x9a, 0xab, 0xcb,
	0x7e, 0x37, 0xa0, 0x2a, 0x38, 0x8a, 0xec, 0xf1, 0xd8, 0x33, 0x21, 0x37, 0xf5, 0xd3, 0x52, 0xe0,
	0x61, 0xac, 0xe3, 0x49, 0x3e, 0x82, 0xfa, 0x28, 0xf4, 0x27, 0x18, 0x0b, 0x67, 0x69, 0x6d, 0xa9,
	0xb7, 0xb2, 0x5d, 0x6e, 0x97, 0xdc, 0x14, 0x22, 0xdf, 0x86, 0x65, 0x73, 0xe9, 0x99, 0x26, 0x6d,
	0x4e, 0x29, 0x2d, 0x83, 0x6f, 0xeb, 0x76, 0x7d, 0x08, 0xc4, 0xd2, 0x66, 0xeb, 0x0c, 0xa6, 0xe4,
	0xb6, 0xb1, 0x1e, 0x65, 0x15, 0xd7, 0x83, 0xf6, 0x4c, 0xff, 0x7a, 0x91, 0x2f, 0x4e, 0x9d, 0x65,
	0x93, 0x93, 0xac, 0x87, 0x9f, 0xfb, 0xe2, 0x74, 0xb6, 0x8d, 0x2b, 0xb9, 0x36, 0x56, 0xda, 0x36,
	0xed, 0xdf, 0xaa, 0xee, 0x5f, 0x1d, 0x09, 0xdd, 0xb9, 0x77, 0x61, 0x55, 0x1b, 0x8f, 0x7d, 0x81,
	0xa6, 0x6f, 0xeb, 0xba, 0x6f, 0x97, 0x15, 0xba, 0xed, 0x0b, 0x54, 0x5d, 0x4b, 0xd6, 0x40, 0xdf,
	0x7b, 0x49, 0x30, 0xdb, 0xdb, 0xa0, 0xb0, 0x17, 0x81, 0x62, 0x74, 0xfe, 0x5b, 0x82, 0x8a, 0xca,
	0x97, 0x0a, 0xb3, 0x8e, 0x65, 0x40, 0xcf, 0x6d, 0xa7, 0xd6, 0xd5, 0xfd, 0x1e, 0x3d, 0x57, 0xa6,
	0x90, 0x1f, 0x1f, 0x4f, 0xd2, 0x0e, 0xad, 0xb9, 0x75, 0x7d, 0xbf, 0x47, 0x95, 0xc9, 0x6c, 0x33,
	0xa0, 0xba, 0x33, 0x2b, 0x6e, 0x5d, 0xdf, 0xef, 0x51, 0x72, 0x0b, 0x5a, 0xfa, 0xdd, 0xbe, 0x37,
	0xe4, 0xdc, 0xec, 0xad, 0xe1, 0xea, 0x1d, 0x6d, 0xed, 0x72, 0x4e, 0x49, 0x3f, 0xed, 0x13, 0xd3,
	0x85, 0xb7, 0x0a, 0xfb, 0x44, 0x2d, 0xcd, 0xf4, 0xca, 0xad, 0x5c, 0xaf, 0x4c, 0xf1, 0xf9, 0x7e,
	0xb9, 0x09, 0x20, 0xa4, 0x1f, 0x4b, 0x23, 0x16, 0x46, 0x17, 0x9b, 0x1a, 0x51, 0x4a, 0xd1, 0xf9,
	0x47, 0x09, 0x2a, 0xaa, 0xca, 0x54, 0xd4, 0xed, 0x76, 0xed, 0x6e, 0x6b, 0x66, 0xb7, 0xe4, 0x23,
	0x00, 0x9b, 0x8e, 0x73, 0xcf, 0xb7, 0x05, 0xd5, 0x30, 0x19, 0x39, 0xdf, 0xca, 0x59, 0x8f, 0xad,
	0x16, 0xa5, 0xd6, 0x6d, 0xf2, 0x3b, 0x00, 0xed, 0xd4, 0xec, 0xab, 0xf2, 0x86, 0x7d, 0xa9, 0x35,
	0x14, 0xed, 0x6b, 0x8a, 0x4f, 0xf7, 0xd5, 0x64, 0x29, 0xd4, 0xfd, 0x73, 0x0d, 0x6e, 0x2e, 0x76,
	0x8d, 0xb6, 0xed, 0x9c, 0xf8, 0x6c, 0x88, 0xea, 0x6b, 0xcb, 0x70, 0xec, 0x15, 0xe9, 0xee, 0x15,
	0x86, 0xe3, 0xfe, 0xac, 0xf4, 0xee, 0x41, 0x15, 0xcf, 0x90, 0x49, 0xbd, 0xc7, 0x8b, 0x74, 0xea,
	0x99, 0x62, 0x7c, 0x7a, 0x3d, 0xb7, 0x46, 0x8d, 0x19, 0xfd, 0x33, 0x1e, 0xc8, 0x09, 0x5c, 0x9b,
	0x7b, 0xad, 0x89, 0xc0, 0xd2, 0xd7, 0x52, 0x40, 0x92, 0x5b, 0xb1, 0xe9, 0xe6, 0x17, 0xb0, 0xac,
	0x74, 0xc5, 0x1b, 0xe8, 0xfd, 0x0a, 0xa7, 0xa2, 0x55, 0x65, 0xf3, 0x4d, 0xaa, 0x32, 0x13, 0x1f,
	0xad, 0x4c, 0xe6, 0xd2, 0x6d, 0x0d, 0xa7, 0xd7, 0x42, 0xb9, 0xd5, 0x69, 0x4d, 0xdd, 0x56, 0xdf,
	0xcd, 0xad, 0xd2, 0xa9, 0xd4, 0xad, 0x9c, 0x5e, 0x0b, 0xf2, 0x7d, 0xf8, 0x20, 0xc2, 0x78, 0x88,
	0x34, 0x9f, 0x11, 0xe1, 0xd4, 0xa6, 0xca, 0x71, 0xd5, 0x10, 0x66, 0x33, 0x23, 0x16, 0x45, 0xbf,
	0xbe, 0x20, 0xfa, 0x9d, 0x3f, 0x95, 0x00, 0xb2, 0xed, 0xe4, 0x1a, 0xb1, 0x94, 0x6f, 0xc4, 0xdf,
	0x42, 0x53, 0x65, 0x27, 0x53, 0xc8, 0xaf, 0xdf, 0x6c, 0x0d, 0x86, 0x63, 0x8d, 0x74, 0xfe, 0x00,
	0x90, 0xed, 0x7e, 0x41, 0xab, 0x2b, 0x99, 0x56, 0x7f, 0x6c, 0x4a, 0xb3, 0x48, 0xaf, 0x57, 0x19,
	0x8e, 0x0f, 0x66, 0x24, 0xfb, 0x63, 0x78, 0x9f, 0x87, 0x74, 0x8e, 0x6a, 0x7a, 0x6d, 0x95, 0x87,
	0x74, 0x86, 0xda, 0xfd, 0xcb, 0x12, 0x3c, 0x48, 0x73, 0x93, 0x9f, 0x4d, 0x7e, 0x39, 0xa7, 0xc8,
	0x8a, 0x2f, 0xe6, 0x27, 0x85, 0xd2, 0xc2, 0xa4, 0xa0, 0x54, 0x2b, 0x88, 0x50, 0x78, 0x63, 0xce,
	0xbc, 0x87, 0x76, 0x81, 0x4d, 0x0d, 0xbd, 0xe4, 0xec, 0x61, 0xde, 0xfe, 0xc8, 0xae, 0x6a, 0x6a,
	0x7f, 0x94, 0xb7, 0x6f, 0x5a, 0x45, 0x9f, 0xda, 0x37, 0xf3, 0xf6, 0xc7, 0x76, 0xac, 0x9b, 0xda,
	0x1f, 0x93, 0x07, 0x40, 0x8c, 0xfd, 0x78, 0x82, 0x9e, 0xcf, 0xa8, 0x17, 0x72, 0x21, 0xad, 0x8e,
	0xe9, 0x81, 0x59, 0x6c, 0x4f, 0x70, 0x8b, 0xd1, 0x7d, 0x2e, 0xa4, 0x0a, 0x54, 0x9e, 0x3c, 0xe6,
	0xcc, 0xd6, 0xca, 0xea, 0x0c, 0xf7, 0x25, 0x67, 0x64, 0x03, 0xae, 0x1a, 0x6a, 0xc2, 0x12, 0x91,
	0xf8, 0xa1, 0x2a, 0xf5, 0x68, 0x64, 0xa7, 0x09, 0xe3, 0xe5, 0x85, 0xb1, 0xec, 0x28, 0x03, 0xf9,
	0x0e, 0x5c, 0x91, 0x5c, 0xfa, 0xa1, 0xa7, 0x3f, 0xe3, 0xda, 0x71, 0x43, 0x73, 0x57, 0x34, 0xac,
	0x4a, 0x42, 0x2d, 0x58, 0x8d, 0xb7, 0x62, 0xc0, 0x63, 0x74, 0x9a, 0x66, 0xbc, 0xd5, 0x37, 0xdd,
	0xff, 0x94, 0xcc, 0x19, 0xe7, 0xc2, 0xb4, 0xe8, 0x64, 0xdc, 0x04, 0xf0, 0x07, 0x03, 0x9e, 0xcc,
	0xca, 0x54, 0xd3, 0x22, 0x66, 0x8c, 0x5d, 0x18, 0x6b, 0xca, 0x85, 0x63, 0xcd, 0xaf, 0x61, 0x79,
	0x26, 0xab, 0xe6, 0x43, 0xdf, 0xda, 0x7c, 0xb2, 0xd8, 0xbe, 0x6f, 0x51, 0x22, 0x6e, 0x2b, 0xab,
	0x06, 0xa1, 0xc6, 0xf0, 0x41, 0x12, 0xc7, 0x7a, 0x6a, 0x0c, 0x30, 0xb6, 0xf9, 0x6c, 0x59, 0xac,
	0x1f, 0x60, 0xdc, 0x15, 0xd0, 0xbb, 0x74, 0xab, 0xf6, 0xac, 0xf7, 0x8d, 0xed, 0xb8, 0xfb, 0xaf,
	0x25, 0x58, 0x7f, 0xd3, 0x5b, 0x3f, 0x0f, 0x84, 0xe4, 0xf1, 0xe4, 0xb2, 0x17, 0xfe, 0x06, 0x5a,
	0x99, 0x32, 0xa5, 0x71, 0xfb, 0xe1, 0xdb, 0xc5, 0xcd, 0xbe, 0x62, 0x23, 0xd3, 0x09, 0x77, 0xd6,
	0x59, 0xe7, 0x8b, 0x32, 0xc0, 0xbb, 0x1e, 0x07, 0xf2, 0x5f, 0xef, 0xf2, 0xdc, 0xd7, 0x9b, 0xdc,
	0x53, 0x45, 0x99, 0x8d, 0xf1, 0x2a, 0x21, 0x56, 0x16, 0x66, 0xe6, 0xf0, 0x00, 0xe3, 0xcb, 0x67,
	0x2a, 0x9a, 0x0e, 0x1e, 0xf6, 0xf3, 0xfd, 0x54, 0xe9, 0xce, 0x6d, 0x3b, 0xb1, 0xc4, 0x28, 0x92,
	0x30, 0x6d, 0x3a, 0xfd, 0xbd, 0x77, 0x35, 0x32, 0x17, 0x4d, 0x35, 0x43, 0xe7, 0xa2, 0x99, 0x1b,
	0xd8, 0x1a, 0x73, 0x03, 0x5b, 0x51, 0x6e, 0x9b, 0x85, 0xb9, 0xfd, 0x67, 0x05, 0xee, 0x5f, 0x10,
	0xf8, 0xec, 0xe8, 0xc9, 0xd9, 0x53, 0x94, 0x7e, 0x10, 0x0a, 0x25, 0xef, 0xf3, 0x7f, 0x05, 0xfc,
	0xf4, 0xd2, 0x0c, 0x16, 0x38, 0x2a, 0xfc, 0x6b, 0xe0, 0xaf, 0x6a, 0x0a, 0x57, 0x11, 0x25, 0x50,
	0xd1, 0xf1, 0x36, 0x59, 0xd3, 0xd7, 0xc4, 0xc9, 0x46, 0x6b, 0x93, 0xaa, 0xe9, 0x58, 0x7d, 0x2d,
	0x3d, 0x67, 0xd8, 0x43, 0xaf, 0x39, 0x44, 0xac, 0xc3, 0xca, 0x38, 0x60, 0x2c, 0x60, 0x43, 0xcf,
	0x58, 0x4d, 0x6e, 0x96, 0x2d, 0xd8, 0xd7, 0x24, 0x75, 0x24, 0x35, 0x5e, 0x3c, 0x21, 0x63, 0xf4,
	0x4f, 0xbd, 0x4d, 0x9b, 0xa8, 0x55, 0x8b, 0x1f, 0x69, 0x78, 0xb3, 0x80, 0xf9, 0xd8, 0xe6, 0x2c,
	0xcf, 0x7c, 0x5c, 0xc0, 0xfc, 0x24, 0x95, 0xc9, 0x1c, 0xf3, 0x93, 0x02, 0xe6, 0x13, 0xab, 0x7b,
	0x79, 0xe6, 0x93, 0xce, 0xdf, 0x66, 0xff, 0x34, 0x99, 0x3b, 0xc6, 0x96, 0x2e, 0x3f, 0xc6, 0x96,
	0x0b, 0x8e, 0xb1, 0x87, 0x50, 0x55, 0x71, 0x4d, 0xfb, 0xf0, 0x47, 0x5f, 0x29, 0x8b, 0x2a, 0x5b,
	0xae, 0xf1, 0x73, 0xff, 0x8b, 0x0a, 0xb4, 0xe7, 0x07, 0x37, 0x72, 0x03, 0x2e, 0x1a, 0xe7, 0xda,
	0xef, 0x91, 0x1e, 0xdc, 0x2d, 0x30, 0x66, 0xf7, 0x3b, 0x31, 0xfa, 0x12, 0x69, 0xbb, 0x74, 0x29,
	0x53, 0x3c, 0xd7, 0x83, 0x4d, 0xbb, 0x4c, 0xba, 0x70, 0xab, 0x80, 0xa9, 0xbe, 0x20, 0x87, 0x89,
	0x1c, 0xf0, 0x08, 0xdb, 0x4b, 0x64, 0x1d, 0x6e, 0x17, 0x79, 0xd3, 0xb3, 0xc3, 0x19, 0xb2, 0xed,
	0x09, 0xb6, 0x2b, 0xe4, 0x21, 0x7c, 0xf7, 0xcd, 0x8b, 0xf3, 0xd9, 0x00, 0x43, 0xa4, 0xdb, 0x93,
	0x2d, 0x1a, 0x05, 0xac, 0x5d, 0x25, 0x77, 0x61, 0xed, 0x02, 0xb7, 0x5b, 0xc7, 0x3e, 0xa3, 0x9c,
	0x21, 0x6d, 0xd7, 0xc8, 0x03, 0xb8, 0x57, 0xc0, 0x4a, 0xff, 0x32, 0xa3, 0x76, 0xfc, 0x89, 0xd5,
	0xbe, 0xeb, 0xe4, 0x36, 0xdc, 0x28, 0x20, 0xa7, 0xaf, 0x6e, 0x37, 0xc8, 0xcf, 0xe0, 0xc7, 0x17,
	0xbc, 0x33, 0x97, 0x2f, 0x95, 0x71, 0x7a, 0x98, 0x48, 0xef, 0x19, 0x93, 0xf1, 0xe4, 0x33, 0x44,
	0x17, 0x5f, 0x25, 0x8c, 0xb6, 0x9b, 0xe4, 0xe7, 0xf0, 0x93, 0xaf, 0xe4, 0xe0, 0x33, 0x1e, 0xbf,
	0xc2, 0x40, 0xb6, 0xe1, 0x9d, 0x97, 0xb0, 0x1b, 0xfb, 0x4c, 0x22, 0xfd, 0x55, 0x30, 0x50, 0x8a,
	0xde, 0x6e, 0x6d, 0x57, 0x3f, 0x2f, 0xfd, 0xb1, 0xf4, 0xde, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x7b, 0x76, 0x34, 0x2f, 0xf6, 0x14, 0x00, 0x00,
}
