// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dota_gcmessages_client_guild_events.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EGuildEventAuditAction int32

const (
	EGuildEventAuditAction_k_EGuildEventAuditAction_Invalid              EGuildEventAuditAction = 0
	EGuildEventAuditAction_k_EGuildEventAuditAction_DevGrant             EGuildEventAuditAction = 1
	EGuildEventAuditAction_k_EGuildEventAuditAction_CompleteContract     EGuildEventAuditAction = 2
	EGuildEventAuditAction_k_EGuildEventAuditAction_CompleteChallenge    EGuildEventAuditAction = 3
	EGuildEventAuditAction_k_EGuildEventAuditAction_CompleteMatch_Winner EGuildEventAuditAction = 4
	EGuildEventAuditAction_k_EGuildEventAuditAction_ChallengeProgress    EGuildEventAuditAction = 5
	EGuildEventAuditAction_k_EGuildEventAuditAction_CompleteMatch_Loser  EGuildEventAuditAction = 6
	EGuildEventAuditAction_k_EGuildEventAuditAction_WeeklyLeaderboard    EGuildEventAuditAction = 7
	EGuildEventAuditAction_k_EGuildEventAuditAction_ManualGrant          EGuildEventAuditAction = 8
)

var EGuildEventAuditAction_name = map[int32]string{
	0: "k_EGuildEventAuditAction_Invalid",
	1: "k_EGuildEventAuditAction_DevGrant",
	2: "k_EGuildEventAuditAction_CompleteContract",
	3: "k_EGuildEventAuditAction_CompleteChallenge",
	4: "k_EGuildEventAuditAction_CompleteMatch_Winner",
	5: "k_EGuildEventAuditAction_ChallengeProgress",
	6: "k_EGuildEventAuditAction_CompleteMatch_Loser",
	7: "k_EGuildEventAuditAction_WeeklyLeaderboard",
	8: "k_EGuildEventAuditAction_ManualGrant",
}

var EGuildEventAuditAction_value = map[string]int32{
	"k_EGuildEventAuditAction_Invalid":              0,
	"k_EGuildEventAuditAction_DevGrant":             1,
	"k_EGuildEventAuditAction_CompleteContract":     2,
	"k_EGuildEventAuditAction_CompleteChallenge":    3,
	"k_EGuildEventAuditAction_CompleteMatch_Winner": 4,
	"k_EGuildEventAuditAction_ChallengeProgress":    5,
	"k_EGuildEventAuditAction_CompleteMatch_Loser":  6,
	"k_EGuildEventAuditAction_WeeklyLeaderboard":    7,
	"k_EGuildEventAuditAction_ManualGrant":          8,
}

func (x EGuildEventAuditAction) Enum() *EGuildEventAuditAction {
	p := new(EGuildEventAuditAction)
	*p = x
	return p
}

func (x EGuildEventAuditAction) String() string {
	return proto.EnumName(EGuildEventAuditAction_name, int32(x))
}

func (x *EGuildEventAuditAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGuildEventAuditAction_value, data, "EGuildEventAuditAction")
	if err != nil {
		return err
	}
	*x = EGuildEventAuditAction(value)
	return nil
}

func (EGuildEventAuditAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{0}
}

type CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse int32

const (
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eInternalError     CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 0
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eSuccess           CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 1
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eTooBusy           CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 2
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eDisabled          CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 3
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eTimeout           CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 4
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eInvalidEvent      CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 5
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eInvalidGuild      CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 6
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eNotMember         CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 7
	CMsgClientToGCRequestAccountGuildEventDataResponse_k_eInvalidGuildEvent CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = 8
)

var CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
	5: "k_eInvalidEvent",
	6: "k_eInvalidGuild",
	7: "k_eNotMember",
	8: "k_eInvalidGuildEvent",
}

var CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse_value = map[string]int32{
	"k_eInternalError":     0,
	"k_eSuccess":           1,
	"k_eTooBusy":           2,
	"k_eDisabled":          3,
	"k_eTimeout":           4,
	"k_eInvalidEvent":      5,
	"k_eInvalidGuild":      6,
	"k_eNotMember":         7,
	"k_eInvalidGuildEvent": 8,
}

func (x CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse) Enum() *CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse {
	p := new(CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse_value, data, "CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{7, 0}
}

type CMsgClientToGCRequestActiveGuildContractsResponse_EResponse int32

const (
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eInternalError     CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 0
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eSuccess           CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 1
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eTooBusy           CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 2
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eDisabled          CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 3
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eTimeout           CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 4
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eInvalidEvent      CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 5
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eInvalidGuild      CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 6
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eNotMember         CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 7
	CMsgClientToGCRequestActiveGuildContractsResponse_k_eInvalidGuildEvent CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = 8
)

var CMsgClientToGCRequestActiveGuildContractsResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
	5: "k_eInvalidEvent",
	6: "k_eInvalidGuild",
	7: "k_eNotMember",
	8: "k_eInvalidGuildEvent",
}

var CMsgClientToGCRequestActiveGuildContractsResponse_EResponse_value = map[string]int32{
	"k_eInternalError":     0,
	"k_eSuccess":           1,
	"k_eTooBusy":           2,
	"k_eDisabled":          3,
	"k_eTimeout":           4,
	"k_eInvalidEvent":      5,
	"k_eInvalidGuild":      6,
	"k_eNotMember":         7,
	"k_eInvalidGuildEvent": 8,
}

func (x CMsgClientToGCRequestActiveGuildContractsResponse_EResponse) Enum() *CMsgClientToGCRequestActiveGuildContractsResponse_EResponse {
	p := new(CMsgClientToGCRequestActiveGuildContractsResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCRequestActiveGuildContractsResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCRequestActiveGuildContractsResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCRequestActiveGuildContractsResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCRequestActiveGuildContractsResponse_EResponse_value, data, "CMsgClientToGCRequestActiveGuildContractsResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCRequestActiveGuildContractsResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCRequestActiveGuildContractsResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{10, 0}
}

type CMsgClientToGCSelectGuildContractResponse_EResponse int32

const (
	CMsgClientToGCSelectGuildContractResponse_k_eInternalError         CMsgClientToGCSelectGuildContractResponse_EResponse = 0
	CMsgClientToGCSelectGuildContractResponse_k_eSuccess               CMsgClientToGCSelectGuildContractResponse_EResponse = 1
	CMsgClientToGCSelectGuildContractResponse_k_eTooBusy               CMsgClientToGCSelectGuildContractResponse_EResponse = 2
	CMsgClientToGCSelectGuildContractResponse_k_eDisabled              CMsgClientToGCSelectGuildContractResponse_EResponse = 3
	CMsgClientToGCSelectGuildContractResponse_k_eTimeout               CMsgClientToGCSelectGuildContractResponse_EResponse = 4
	CMsgClientToGCSelectGuildContractResponse_k_eInvalidEvent          CMsgClientToGCSelectGuildContractResponse_EResponse = 5
	CMsgClientToGCSelectGuildContractResponse_k_eInvalidGuild          CMsgClientToGCSelectGuildContractResponse_EResponse = 6
	CMsgClientToGCSelectGuildContractResponse_k_eNotMember             CMsgClientToGCSelectGuildContractResponse_EResponse = 7
	CMsgClientToGCSelectGuildContractResponse_k_eInvalidGuildEvent     CMsgClientToGCSelectGuildContractResponse_EResponse = 8
	CMsgClientToGCSelectGuildContractResponse_k_eInvalidContractID     CMsgClientToGCSelectGuildContractResponse_EResponse = 9
	CMsgClientToGCSelectGuildContractResponse_k_eAlreadyAssigned       CMsgClientToGCSelectGuildContractResponse_EResponse = 10
	CMsgClientToGCSelectGuildContractResponse_k_eInvalidContractSlot   CMsgClientToGCSelectGuildContractResponse_EResponse = 11
	CMsgClientToGCSelectGuildContractResponse_k_eContractSlotLocked    CMsgClientToGCSelectGuildContractResponse_EResponse = 12
	CMsgClientToGCSelectGuildContractResponse_k_eContractSlotCooldown  CMsgClientToGCSelectGuildContractResponse_EResponse = 13
	CMsgClientToGCSelectGuildContractResponse_k_eContractDuplicate     CMsgClientToGCSelectGuildContractResponse_EResponse = 14
	CMsgClientToGCSelectGuildContractResponse_k_eContractSlotTimeError CMsgClientToGCSelectGuildContractResponse_EResponse = 15
)

var CMsgClientToGCSelectGuildContractResponse_EResponse_name = map[int32]string{
	0:  "k_eInternalError",
	1:  "k_eSuccess",
	2:  "k_eTooBusy",
	3:  "k_eDisabled",
	4:  "k_eTimeout",
	5:  "k_eInvalidEvent",
	6:  "k_eInvalidGuild",
	7:  "k_eNotMember",
	8:  "k_eInvalidGuildEvent",
	9:  "k_eInvalidContractID",
	10: "k_eAlreadyAssigned",
	11: "k_eInvalidContractSlot",
	12: "k_eContractSlotLocked",
	13: "k_eContractSlotCooldown",
	14: "k_eContractDuplicate",
	15: "k_eContractSlotTimeError",
}

var CMsgClientToGCSelectGuildContractResponse_EResponse_value = map[string]int32{
	"k_eInternalError":         0,
	"k_eSuccess":               1,
	"k_eTooBusy":               2,
	"k_eDisabled":              3,
	"k_eTimeout":               4,
	"k_eInvalidEvent":          5,
	"k_eInvalidGuild":          6,
	"k_eNotMember":             7,
	"k_eInvalidGuildEvent":     8,
	"k_eInvalidContractID":     9,
	"k_eAlreadyAssigned":       10,
	"k_eInvalidContractSlot":   11,
	"k_eContractSlotLocked":    12,
	"k_eContractSlotCooldown":  13,
	"k_eContractDuplicate":     14,
	"k_eContractSlotTimeError": 15,
}

func (x CMsgClientToGCSelectGuildContractResponse_EResponse) Enum() *CMsgClientToGCSelectGuildContractResponse_EResponse {
	p := new(CMsgClientToGCSelectGuildContractResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCSelectGuildContractResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCSelectGuildContractResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCSelectGuildContractResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCSelectGuildContractResponse_EResponse_value, data, "CMsgClientToGCSelectGuildContractResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCSelectGuildContractResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCSelectGuildContractResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{13, 0}
}

type CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse int32

const (
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eInternalError     CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 0
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eSuccess           CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 1
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eTooBusy           CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 2
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eDisabled          CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 3
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eTimeout           CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 4
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eInvalidEvent      CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 5
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eInvalidGuild      CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 6
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eNotMember         CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 7
	CMsgClientToGCRequestActiveGuildChallengeResponse_k_eInvalidGuildEvent CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = 8
)

var CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
	5: "k_eInvalidEvent",
	6: "k_eInvalidGuild",
	7: "k_eNotMember",
	8: "k_eInvalidGuildEvent",
}

var CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse_value = map[string]int32{
	"k_eInternalError":     0,
	"k_eSuccess":           1,
	"k_eTooBusy":           2,
	"k_eDisabled":          3,
	"k_eTimeout":           4,
	"k_eInvalidEvent":      5,
	"k_eInvalidGuild":      6,
	"k_eNotMember":         7,
	"k_eInvalidGuildEvent": 8,
}

func (x CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse) Enum() *CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse {
	p := new(CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse_value, data, "CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{15, 0}
}

type CMsgClientToGCRequestGuildEventMembersResponse_EResponse int32

const (
	CMsgClientToGCRequestGuildEventMembersResponse_k_eInternalError     CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 0
	CMsgClientToGCRequestGuildEventMembersResponse_k_eSuccess           CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 1
	CMsgClientToGCRequestGuildEventMembersResponse_k_eTooBusy           CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 2
	CMsgClientToGCRequestGuildEventMembersResponse_k_eDisabled          CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 3
	CMsgClientToGCRequestGuildEventMembersResponse_k_eTimeout           CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 4
	CMsgClientToGCRequestGuildEventMembersResponse_k_eInvalidEvent      CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 5
	CMsgClientToGCRequestGuildEventMembersResponse_k_eInvalidGuild      CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 6
	CMsgClientToGCRequestGuildEventMembersResponse_k_eNotMember         CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 7
	CMsgClientToGCRequestGuildEventMembersResponse_k_eInvalidGuildEvent CMsgClientToGCRequestGuildEventMembersResponse_EResponse = 8
)

var CMsgClientToGCRequestGuildEventMembersResponse_EResponse_name = map[int32]string{
	0: "k_eInternalError",
	1: "k_eSuccess",
	2: "k_eTooBusy",
	3: "k_eDisabled",
	4: "k_eTimeout",
	5: "k_eInvalidEvent",
	6: "k_eInvalidGuild",
	7: "k_eNotMember",
	8: "k_eInvalidGuildEvent",
}

var CMsgClientToGCRequestGuildEventMembersResponse_EResponse_value = map[string]int32{
	"k_eInternalError":     0,
	"k_eSuccess":           1,
	"k_eTooBusy":           2,
	"k_eDisabled":          3,
	"k_eTimeout":           4,
	"k_eInvalidEvent":      5,
	"k_eInvalidGuild":      6,
	"k_eNotMember":         7,
	"k_eInvalidGuildEvent": 8,
}

func (x CMsgClientToGCRequestGuildEventMembersResponse_EResponse) Enum() *CMsgClientToGCRequestGuildEventMembersResponse_EResponse {
	p := new(CMsgClientToGCRequestGuildEventMembersResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCRequestGuildEventMembersResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCRequestGuildEventMembersResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCRequestGuildEventMembersResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCRequestGuildEventMembersResponse_EResponse_value, data, "CMsgClientToGCRequestGuildEventMembersResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCRequestGuildEventMembersResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCRequestGuildEventMembersResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{18, 0}
}

type CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse int32

const (
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eInternalError     CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 0
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eSuccess           CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 1
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eTooBusy           CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 2
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eDisabled          CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 3
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eTimeout           CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 4
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eInvalidEvent      CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 5
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eInvalidGuild      CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 6
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eNotMember         CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 7
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eInvalidGuildEvent CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 8
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eDoesNotQualify    CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 9
	CMsgClientToGCClaimLeaderboardRewardsResponse_k_eAlreadyClaimed    CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = 10
)

var CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse_name = map[int32]string{
	0:  "k_eInternalError",
	1:  "k_eSuccess",
	2:  "k_eTooBusy",
	3:  "k_eDisabled",
	4:  "k_eTimeout",
	5:  "k_eInvalidEvent",
	6:  "k_eInvalidGuild",
	7:  "k_eNotMember",
	8:  "k_eInvalidGuildEvent",
	9:  "k_eDoesNotQualify",
	10: "k_eAlreadyClaimed",
}

var CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse_value = map[string]int32{
	"k_eInternalError":     0,
	"k_eSuccess":           1,
	"k_eTooBusy":           2,
	"k_eDisabled":          3,
	"k_eTimeout":           4,
	"k_eInvalidEvent":      5,
	"k_eInvalidGuild":      6,
	"k_eNotMember":         7,
	"k_eInvalidGuildEvent": 8,
	"k_eDoesNotQualify":    9,
	"k_eAlreadyClaimed":    10,
}

func (x CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse) Enum() *CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse {
	p := new(CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse) String() string {
	return proto.EnumName(CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse_name, int32(x))
}

func (x *CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse_value, data, "CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse")
	if err != nil {
		return err
	}
	*x = CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse(value)
	return nil
}

func (CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{22, 0}
}

type CMsgGuildContract struct {
	ContractId           *uint64  `protobuf:"varint,1,opt,name=contract_id,json=contractId" json:"contract_id,omitempty"`
	ChallengeInstanceId  *uint32  `protobuf:"varint,2,opt,name=challenge_instance_id,json=challengeInstanceId" json:"challenge_instance_id,omitempty"`
	ChallengeParameter   *uint32  `protobuf:"varint,3,opt,name=challenge_parameter,json=challengeParameter" json:"challenge_parameter,omitempty"`
	ChallengeTimestamp   *uint32  `protobuf:"varint,4,opt,name=challenge_timestamp,json=challengeTimestamp" json:"challenge_timestamp,omitempty"`
	AssignedAccountId    *uint32  `protobuf:"varint,5,opt,name=assigned_account_id,json=assignedAccountId" json:"assigned_account_id,omitempty"`
	ContractFlags        *uint32  `protobuf:"varint,6,opt,name=contract_flags,json=contractFlags" json:"contract_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGuildContract) Reset()         { *m = CMsgGuildContract{} }
func (m *CMsgGuildContract) String() string { return proto.CompactTextString(m) }
func (*CMsgGuildContract) ProtoMessage()    {}
func (*CMsgGuildContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{0}
}

func (m *CMsgGuildContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGuildContract.Unmarshal(m, b)
}
func (m *CMsgGuildContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGuildContract.Marshal(b, m, deterministic)
}
func (m *CMsgGuildContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGuildContract.Merge(m, src)
}
func (m *CMsgGuildContract) XXX_Size() int {
	return xxx_messageInfo_CMsgGuildContract.Size(m)
}
func (m *CMsgGuildContract) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGuildContract.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGuildContract proto.InternalMessageInfo

func (m *CMsgGuildContract) GetContractId() uint64 {
	if m != nil && m.ContractId != nil {
		return *m.ContractId
	}
	return 0
}

func (m *CMsgGuildContract) GetChallengeInstanceId() uint32 {
	if m != nil && m.ChallengeInstanceId != nil {
		return *m.ChallengeInstanceId
	}
	return 0
}

func (m *CMsgGuildContract) GetChallengeParameter() uint32 {
	if m != nil && m.ChallengeParameter != nil {
		return *m.ChallengeParameter
	}
	return 0
}

func (m *CMsgGuildContract) GetChallengeTimestamp() uint32 {
	if m != nil && m.ChallengeTimestamp != nil {
		return *m.ChallengeTimestamp
	}
	return 0
}

func (m *CMsgGuildContract) GetAssignedAccountId() uint32 {
	if m != nil && m.AssignedAccountId != nil {
		return *m.AssignedAccountId
	}
	return 0
}

func (m *CMsgGuildContract) GetContractFlags() uint32 {
	if m != nil && m.ContractFlags != nil {
		return *m.ContractFlags
	}
	return 0
}

type CMsgGuildContractSlot struct {
	Contract             *CMsgGuildContract `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CMsgGuildContractSlot) Reset()         { *m = CMsgGuildContractSlot{} }
func (m *CMsgGuildContractSlot) String() string { return proto.CompactTextString(m) }
func (*CMsgGuildContractSlot) ProtoMessage()    {}
func (*CMsgGuildContractSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{1}
}

func (m *CMsgGuildContractSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGuildContractSlot.Unmarshal(m, b)
}
func (m *CMsgGuildContractSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGuildContractSlot.Marshal(b, m, deterministic)
}
func (m *CMsgGuildContractSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGuildContractSlot.Merge(m, src)
}
func (m *CMsgGuildContractSlot) XXX_Size() int {
	return xxx_messageInfo_CMsgGuildContractSlot.Size(m)
}
func (m *CMsgGuildContractSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGuildContractSlot.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGuildContractSlot proto.InternalMessageInfo

func (m *CMsgGuildContractSlot) GetContract() *CMsgGuildContract {
	if m != nil {
		return m.Contract
	}
	return nil
}

type CMsgAccountGuildEventData struct {
	GuildPoints                 *uint32                  `protobuf:"varint,1,opt,name=guild_points,json=guildPoints" json:"guild_points,omitempty"`
	ContractsRefreshedTimestamp *uint32                  `protobuf:"varint,2,opt,name=contracts_refreshed_timestamp,json=contractsRefreshedTimestamp" json:"contracts_refreshed_timestamp,omitempty"`
	ContractSlots               []*CMsgGuildContractSlot `protobuf:"bytes,3,rep,name=contract_slots,json=contractSlots" json:"contract_slots,omitempty"`
	CompletedChallengeCount     *uint32                  `protobuf:"varint,4,opt,name=completed_challenge_count,json=completedChallengeCount" json:"completed_challenge_count,omitempty"`
	ChallengesRefreshTimestamp  *uint32                  `protobuf:"varint,5,opt,name=challenges_refresh_timestamp,json=challengesRefreshTimestamp" json:"challenges_refresh_timestamp,omitempty"`
	GuildWeeklyPercentile       *uint32                  `protobuf:"varint,6,opt,name=guild_weekly_percentile,json=guildWeeklyPercentile" json:"guild_weekly_percentile,omitempty"`
	GuildWeeklyLastTimestamp    *uint32                  `protobuf:"varint,7,opt,name=guild_weekly_last_timestamp,json=guildWeeklyLastTimestamp" json:"guild_weekly_last_timestamp,omitempty"`
	LastWeeklyClaimTime         *uint32                  `protobuf:"varint,8,opt,name=last_weekly_claim_time,json=lastWeeklyClaimTime" json:"last_weekly_claim_time,omitempty"`
	GuildCurrentPercentile      *uint32                  `protobuf:"varint,9,opt,name=guild_current_percentile,json=guildCurrentPercentile" json:"guild_current_percentile,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                 `json:"-"`
	XXX_unrecognized            []byte                   `json:"-"`
	XXX_sizecache               int32                    `json:"-"`
}

func (m *CMsgAccountGuildEventData) Reset()         { *m = CMsgAccountGuildEventData{} }
func (m *CMsgAccountGuildEventData) String() string { return proto.CompactTextString(m) }
func (*CMsgAccountGuildEventData) ProtoMessage()    {}
func (*CMsgAccountGuildEventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{2}
}

func (m *CMsgAccountGuildEventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgAccountGuildEventData.Unmarshal(m, b)
}
func (m *CMsgAccountGuildEventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgAccountGuildEventData.Marshal(b, m, deterministic)
}
func (m *CMsgAccountGuildEventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgAccountGuildEventData.Merge(m, src)
}
func (m *CMsgAccountGuildEventData) XXX_Size() int {
	return xxx_messageInfo_CMsgAccountGuildEventData.Size(m)
}
func (m *CMsgAccountGuildEventData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgAccountGuildEventData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgAccountGuildEventData proto.InternalMessageInfo

func (m *CMsgAccountGuildEventData) GetGuildPoints() uint32 {
	if m != nil && m.GuildPoints != nil {
		return *m.GuildPoints
	}
	return 0
}

func (m *CMsgAccountGuildEventData) GetContractsRefreshedTimestamp() uint32 {
	if m != nil && m.ContractsRefreshedTimestamp != nil {
		return *m.ContractsRefreshedTimestamp
	}
	return 0
}

func (m *CMsgAccountGuildEventData) GetContractSlots() []*CMsgGuildContractSlot {
	if m != nil {
		return m.ContractSlots
	}
	return nil
}

func (m *CMsgAccountGuildEventData) GetCompletedChallengeCount() uint32 {
	if m != nil && m.CompletedChallengeCount != nil {
		return *m.CompletedChallengeCount
	}
	return 0
}

func (m *CMsgAccountGuildEventData) GetChallengesRefreshTimestamp() uint32 {
	if m != nil && m.ChallengesRefreshTimestamp != nil {
		return *m.ChallengesRefreshTimestamp
	}
	return 0
}

func (m *CMsgAccountGuildEventData) GetGuildWeeklyPercentile() uint32 {
	if m != nil && m.GuildWeeklyPercentile != nil {
		return *m.GuildWeeklyPercentile
	}
	return 0
}

func (m *CMsgAccountGuildEventData) GetGuildWeeklyLastTimestamp() uint32 {
	if m != nil && m.GuildWeeklyLastTimestamp != nil {
		return *m.GuildWeeklyLastTimestamp
	}
	return 0
}

func (m *CMsgAccountGuildEventData) GetLastWeeklyClaimTime() uint32 {
	if m != nil && m.LastWeeklyClaimTime != nil {
		return *m.LastWeeklyClaimTime
	}
	return 0
}

func (m *CMsgAccountGuildEventData) GetGuildCurrentPercentile() uint32 {
	if m != nil && m.GuildCurrentPercentile != nil {
		return *m.GuildCurrentPercentile
	}
	return 0
}

type CMsgGuildActiveContracts struct {
	ContractsRefreshedTimestamp *uint32              `protobuf:"varint,1,opt,name=contracts_refreshed_timestamp,json=contractsRefreshedTimestamp" json:"contracts_refreshed_timestamp,omitempty"`
	Contracts                   []*CMsgGuildContract `protobuf:"bytes,2,rep,name=contracts" json:"contracts,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}             `json:"-"`
	XXX_unrecognized            []byte               `json:"-"`
	XXX_sizecache               int32                `json:"-"`
}

func (m *CMsgGuildActiveContracts) Reset()         { *m = CMsgGuildActiveContracts{} }
func (m *CMsgGuildActiveContracts) String() string { return proto.CompactTextString(m) }
func (*CMsgGuildActiveContracts) ProtoMessage()    {}
func (*CMsgGuildActiveContracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{3}
}

func (m *CMsgGuildActiveContracts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGuildActiveContracts.Unmarshal(m, b)
}
func (m *CMsgGuildActiveContracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGuildActiveContracts.Marshal(b, m, deterministic)
}
func (m *CMsgGuildActiveContracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGuildActiveContracts.Merge(m, src)
}
func (m *CMsgGuildActiveContracts) XXX_Size() int {
	return xxx_messageInfo_CMsgGuildActiveContracts.Size(m)
}
func (m *CMsgGuildActiveContracts) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGuildActiveContracts.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGuildActiveContracts proto.InternalMessageInfo

func (m *CMsgGuildActiveContracts) GetContractsRefreshedTimestamp() uint32 {
	if m != nil && m.ContractsRefreshedTimestamp != nil {
		return *m.ContractsRefreshedTimestamp
	}
	return 0
}

func (m *CMsgGuildActiveContracts) GetContracts() []*CMsgGuildContract {
	if m != nil {
		return m.Contracts
	}
	return nil
}

type CMsgGuildChallenge struct {
	ChallengeInstanceId  *uint32  `protobuf:"varint,1,opt,name=challenge_instance_id,json=challengeInstanceId" json:"challenge_instance_id,omitempty"`
	ChallengeParameter   *uint32  `protobuf:"varint,2,opt,name=challenge_parameter,json=challengeParameter" json:"challenge_parameter,omitempty"`
	ChallengeTimestamp   *uint32  `protobuf:"varint,3,opt,name=challenge_timestamp,json=challengeTimestamp" json:"challenge_timestamp,omitempty"`
	ChallengeProgress    *uint32  `protobuf:"varint,4,opt,name=challenge_progress,json=challengeProgress" json:"challenge_progress,omitempty"`
	ChallengeFlags       *uint32  `protobuf:"varint,5,opt,name=challenge_flags,json=challengeFlags" json:"challenge_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGuildChallenge) Reset()         { *m = CMsgGuildChallenge{} }
func (m *CMsgGuildChallenge) String() string { return proto.CompactTextString(m) }
func (*CMsgGuildChallenge) ProtoMessage()    {}
func (*CMsgGuildChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{4}
}

func (m *CMsgGuildChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGuildChallenge.Unmarshal(m, b)
}
func (m *CMsgGuildChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGuildChallenge.Marshal(b, m, deterministic)
}
func (m *CMsgGuildChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGuildChallenge.Merge(m, src)
}
func (m *CMsgGuildChallenge) XXX_Size() int {
	return xxx_messageInfo_CMsgGuildChallenge.Size(m)
}
func (m *CMsgGuildChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGuildChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGuildChallenge proto.InternalMessageInfo

func (m *CMsgGuildChallenge) GetChallengeInstanceId() uint32 {
	if m != nil && m.ChallengeInstanceId != nil {
		return *m.ChallengeInstanceId
	}
	return 0
}

func (m *CMsgGuildChallenge) GetChallengeParameter() uint32 {
	if m != nil && m.ChallengeParameter != nil {
		return *m.ChallengeParameter
	}
	return 0
}

func (m *CMsgGuildChallenge) GetChallengeTimestamp() uint32 {
	if m != nil && m.ChallengeTimestamp != nil {
		return *m.ChallengeTimestamp
	}
	return 0
}

func (m *CMsgGuildChallenge) GetChallengeProgress() uint32 {
	if m != nil && m.ChallengeProgress != nil {
		return *m.ChallengeProgress
	}
	return 0
}

func (m *CMsgGuildChallenge) GetChallengeFlags() uint32 {
	if m != nil && m.ChallengeFlags != nil {
		return *m.ChallengeFlags
	}
	return 0
}

type CMsgGuildEventMember struct {
	AccountId            *uint32  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	GuildPointsEarned    *uint32  `protobuf:"varint,2,opt,name=guild_points_earned,json=guildPointsEarned" json:"guild_points_earned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGuildEventMember) Reset()         { *m = CMsgGuildEventMember{} }
func (m *CMsgGuildEventMember) String() string { return proto.CompactTextString(m) }
func (*CMsgGuildEventMember) ProtoMessage()    {}
func (*CMsgGuildEventMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{5}
}

func (m *CMsgGuildEventMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGuildEventMember.Unmarshal(m, b)
}
func (m *CMsgGuildEventMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGuildEventMember.Marshal(b, m, deterministic)
}
func (m *CMsgGuildEventMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGuildEventMember.Merge(m, src)
}
func (m *CMsgGuildEventMember) XXX_Size() int {
	return xxx_messageInfo_CMsgGuildEventMember.Size(m)
}
func (m *CMsgGuildEventMember) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGuildEventMember.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGuildEventMember proto.InternalMessageInfo

func (m *CMsgGuildEventMember) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgGuildEventMember) GetGuildPointsEarned() uint32 {
	if m != nil && m.GuildPointsEarned != nil {
		return *m.GuildPointsEarned
	}
	return 0
}

type CMsgClientToGCRequestAccountGuildEventData struct {
	GuildId              *uint32  `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent  `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCRequestAccountGuildEventData) Reset() {
	*m = CMsgClientToGCRequestAccountGuildEventData{}
}
func (m *CMsgClientToGCRequestAccountGuildEventData) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCRequestAccountGuildEventData) ProtoMessage() {}
func (*CMsgClientToGCRequestAccountGuildEventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{6}
}

func (m *CMsgClientToGCRequestAccountGuildEventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventData.Unmarshal(m, b)
}
func (m *CMsgClientToGCRequestAccountGuildEventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventData.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCRequestAccountGuildEventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventData.Merge(m, src)
}
func (m *CMsgClientToGCRequestAccountGuildEventData) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventData.Size(m)
}
func (m *CMsgClientToGCRequestAccountGuildEventData) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventData.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventData proto.InternalMessageInfo

const Default_CMsgClientToGCRequestAccountGuildEventData_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgClientToGCRequestAccountGuildEventData) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgClientToGCRequestAccountGuildEventData) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgClientToGCRequestAccountGuildEventData_EventId
}

type CMsgClientToGCRequestAccountGuildEventDataResponse struct {
	Result               *CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse `protobuf:"varint,1,opt,name=result,enum=protocol.CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse,def=0" json:"result,omitempty"`
	EventId              *EEvent                                                       `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	EventData            *CMsgAccountGuildEventData                                    `protobuf:"bytes,3,opt,name=event_data,json=eventData" json:"event_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                      `json:"-"`
	XXX_unrecognized     []byte                                                        `json:"-"`
	XXX_sizecache        int32                                                         `json:"-"`
}

func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) Reset() {
	*m = CMsgClientToGCRequestAccountGuildEventDataResponse{}
}
func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCRequestAccountGuildEventDataResponse) ProtoMessage() {}
func (*CMsgClientToGCRequestAccountGuildEventDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{7}
}

func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventDataResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventDataResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventDataResponse.Merge(m, src)
}
func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventDataResponse.Size(m)
}
func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCRequestAccountGuildEventDataResponse proto.InternalMessageInfo

const Default_CMsgClientToGCRequestAccountGuildEventDataResponse_Result CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse = CMsgClientToGCRequestAccountGuildEventDataResponse_k_eInternalError
const Default_CMsgClientToGCRequestAccountGuildEventDataResponse_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) GetResult() CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgClientToGCRequestAccountGuildEventDataResponse_Result
}

func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgClientToGCRequestAccountGuildEventDataResponse_EventId
}

func (m *CMsgClientToGCRequestAccountGuildEventDataResponse) GetEventData() *CMsgAccountGuildEventData {
	if m != nil {
		return m.EventData
	}
	return nil
}

type CMsgGCToClientAccountGuildEventDataUpdated struct {
	GuildId              *uint32                    `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent                    `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	UpdateFlags          *uint32                    `protobuf:"varint,3,opt,name=update_flags,json=updateFlags" json:"update_flags,omitempty"`
	GuildEventData       *CMsgAccountGuildEventData `protobuf:"bytes,4,opt,name=guild_event_data,json=guildEventData" json:"guild_event_data,omitempty"`
	ContractsUpdated     *bool                      `protobuf:"varint,5,opt,name=contracts_updated,json=contractsUpdated" json:"contracts_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CMsgGCToClientAccountGuildEventDataUpdated) Reset() {
	*m = CMsgGCToClientAccountGuildEventDataUpdated{}
}
func (m *CMsgGCToClientAccountGuildEventDataUpdated) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgGCToClientAccountGuildEventDataUpdated) ProtoMessage() {}
func (*CMsgGCToClientAccountGuildEventDataUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{8}
}

func (m *CMsgGCToClientAccountGuildEventDataUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientAccountGuildEventDataUpdated.Unmarshal(m, b)
}
func (m *CMsgGCToClientAccountGuildEventDataUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientAccountGuildEventDataUpdated.Marshal(b, m, deterministic)
}
func (m *CMsgGCToClientAccountGuildEventDataUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientAccountGuildEventDataUpdated.Merge(m, src)
}
func (m *CMsgGCToClientAccountGuildEventDataUpdated) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientAccountGuildEventDataUpdated.Size(m)
}
func (m *CMsgGCToClientAccountGuildEventDataUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientAccountGuildEventDataUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientAccountGuildEventDataUpdated proto.InternalMessageInfo

const Default_CMsgGCToClientAccountGuildEventDataUpdated_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgGCToClientAccountGuildEventDataUpdated) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgGCToClientAccountGuildEventDataUpdated) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgGCToClientAccountGuildEventDataUpdated_EventId
}

func (m *CMsgGCToClientAccountGuildEventDataUpdated) GetUpdateFlags() uint32 {
	if m != nil && m.UpdateFlags != nil {
		return *m.UpdateFlags
	}
	return 0
}

func (m *CMsgGCToClientAccountGuildEventDataUpdated) GetGuildEventData() *CMsgAccountGuildEventData {
	if m != nil {
		return m.GuildEventData
	}
	return nil
}

func (m *CMsgGCToClientAccountGuildEventDataUpdated) GetContractsUpdated() bool {
	if m != nil && m.ContractsUpdated != nil {
		return *m.ContractsUpdated
	}
	return false
}

type CMsgClientToGCRequestActiveGuildContracts struct {
	GuildId              *uint32  `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent  `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCRequestActiveGuildContracts) Reset() {
	*m = CMsgClientToGCRequestActiveGuildContracts{}
}
func (m *CMsgClientToGCRequestActiveGuildContracts) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCRequestActiveGuildContracts) ProtoMessage() {}
func (*CMsgClientToGCRequestActiveGuildContracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{9}
}

func (m *CMsgClientToGCRequestActiveGuildContracts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildContracts.Unmarshal(m, b)
}
func (m *CMsgClientToGCRequestActiveGuildContracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildContracts.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCRequestActiveGuildContracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCRequestActiveGuildContracts.Merge(m, src)
}
func (m *CMsgClientToGCRequestActiveGuildContracts) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildContracts.Size(m)
}
func (m *CMsgClientToGCRequestActiveGuildContracts) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCRequestActiveGuildContracts.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCRequestActiveGuildContracts proto.InternalMessageInfo

const Default_CMsgClientToGCRequestActiveGuildContracts_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgClientToGCRequestActiveGuildContracts) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgClientToGCRequestActiveGuildContracts) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgClientToGCRequestActiveGuildContracts_EventId
}

type CMsgClientToGCRequestActiveGuildContractsResponse struct {
	Result               *CMsgClientToGCRequestActiveGuildContractsResponse_EResponse `protobuf:"varint,1,opt,name=result,enum=protocol.CMsgClientToGCRequestActiveGuildContractsResponse_EResponse,def=0" json:"result,omitempty"`
	ActiveContracts      *CMsgGuildActiveContracts                                    `protobuf:"bytes,2,opt,name=active_contracts,json=activeContracts" json:"active_contracts,omitempty"`
	ActiveChallenges     *CMsgGuildChallenge                                          `protobuf:"bytes,3,opt,name=active_challenges,json=activeChallenges" json:"active_challenges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *CMsgClientToGCRequestActiveGuildContractsResponse) Reset() {
	*m = CMsgClientToGCRequestActiveGuildContractsResponse{}
}
func (m *CMsgClientToGCRequestActiveGuildContractsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCRequestActiveGuildContractsResponse) ProtoMessage() {}
func (*CMsgClientToGCRequestActiveGuildContractsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{10}
}

func (m *CMsgClientToGCRequestActiveGuildContractsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildContractsResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCRequestActiveGuildContractsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildContractsResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCRequestActiveGuildContractsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCRequestActiveGuildContractsResponse.Merge(m, src)
}
func (m *CMsgClientToGCRequestActiveGuildContractsResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildContractsResponse.Size(m)
}
func (m *CMsgClientToGCRequestActiveGuildContractsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCRequestActiveGuildContractsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCRequestActiveGuildContractsResponse proto.InternalMessageInfo

const Default_CMsgClientToGCRequestActiveGuildContractsResponse_Result CMsgClientToGCRequestActiveGuildContractsResponse_EResponse = CMsgClientToGCRequestActiveGuildContractsResponse_k_eInternalError

func (m *CMsgClientToGCRequestActiveGuildContractsResponse) GetResult() CMsgClientToGCRequestActiveGuildContractsResponse_EResponse {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgClientToGCRequestActiveGuildContractsResponse_Result
}

func (m *CMsgClientToGCRequestActiveGuildContractsResponse) GetActiveContracts() *CMsgGuildActiveContracts {
	if m != nil {
		return m.ActiveContracts
	}
	return nil
}

func (m *CMsgClientToGCRequestActiveGuildContractsResponse) GetActiveChallenges() *CMsgGuildChallenge {
	if m != nil {
		return m.ActiveChallenges
	}
	return nil
}

type CMsgGCToClientActiveGuildContractsUpdated struct {
	GuildId              *uint32  `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent  `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGCToClientActiveGuildContractsUpdated) Reset() {
	*m = CMsgGCToClientActiveGuildContractsUpdated{}
}
func (m *CMsgGCToClientActiveGuildContractsUpdated) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgGCToClientActiveGuildContractsUpdated) ProtoMessage() {}
func (*CMsgGCToClientActiveGuildContractsUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{11}
}

func (m *CMsgGCToClientActiveGuildContractsUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientActiveGuildContractsUpdated.Unmarshal(m, b)
}
func (m *CMsgGCToClientActiveGuildContractsUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientActiveGuildContractsUpdated.Marshal(b, m, deterministic)
}
func (m *CMsgGCToClientActiveGuildContractsUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientActiveGuildContractsUpdated.Merge(m, src)
}
func (m *CMsgGCToClientActiveGuildContractsUpdated) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientActiveGuildContractsUpdated.Size(m)
}
func (m *CMsgGCToClientActiveGuildContractsUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientActiveGuildContractsUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientActiveGuildContractsUpdated proto.InternalMessageInfo

const Default_CMsgGCToClientActiveGuildContractsUpdated_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgGCToClientActiveGuildContractsUpdated) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgGCToClientActiveGuildContractsUpdated) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgGCToClientActiveGuildContractsUpdated_EventId
}

type CMsgClientToGCSelectGuildContract struct {
	GuildId              *uint32  `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent  `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	ContractId           *uint64  `protobuf:"varint,3,opt,name=contract_id,json=contractId" json:"contract_id,omitempty"`
	ContractSlot         *uint32  `protobuf:"varint,4,opt,name=contract_slot,json=contractSlot" json:"contract_slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCSelectGuildContract) Reset()         { *m = CMsgClientToGCSelectGuildContract{} }
func (m *CMsgClientToGCSelectGuildContract) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCSelectGuildContract) ProtoMessage()    {}
func (*CMsgClientToGCSelectGuildContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{12}
}

func (m *CMsgClientToGCSelectGuildContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCSelectGuildContract.Unmarshal(m, b)
}
func (m *CMsgClientToGCSelectGuildContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCSelectGuildContract.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCSelectGuildContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCSelectGuildContract.Merge(m, src)
}
func (m *CMsgClientToGCSelectGuildContract) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCSelectGuildContract.Size(m)
}
func (m *CMsgClientToGCSelectGuildContract) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCSelectGuildContract.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCSelectGuildContract proto.InternalMessageInfo

const Default_CMsgClientToGCSelectGuildContract_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgClientToGCSelectGuildContract) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgClientToGCSelectGuildContract) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgClientToGCSelectGuildContract_EventId
}

func (m *CMsgClientToGCSelectGuildContract) GetContractId() uint64 {
	if m != nil && m.ContractId != nil {
		return *m.ContractId
	}
	return 0
}

func (m *CMsgClientToGCSelectGuildContract) GetContractSlot() uint32 {
	if m != nil && m.ContractSlot != nil {
		return *m.ContractSlot
	}
	return 0
}

type CMsgClientToGCSelectGuildContractResponse struct {
	Result               *CMsgClientToGCSelectGuildContractResponse_EResponse `protobuf:"varint,1,opt,name=result,enum=protocol.CMsgClientToGCSelectGuildContractResponse_EResponse,def=0" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *CMsgClientToGCSelectGuildContractResponse) Reset() {
	*m = CMsgClientToGCSelectGuildContractResponse{}
}
func (m *CMsgClientToGCSelectGuildContractResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCSelectGuildContractResponse) ProtoMessage() {}
func (*CMsgClientToGCSelectGuildContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{13}
}

func (m *CMsgClientToGCSelectGuildContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCSelectGuildContractResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCSelectGuildContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCSelectGuildContractResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCSelectGuildContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCSelectGuildContractResponse.Merge(m, src)
}
func (m *CMsgClientToGCSelectGuildContractResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCSelectGuildContractResponse.Size(m)
}
func (m *CMsgClientToGCSelectGuildContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCSelectGuildContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCSelectGuildContractResponse proto.InternalMessageInfo

const Default_CMsgClientToGCSelectGuildContractResponse_Result CMsgClientToGCSelectGuildContractResponse_EResponse = CMsgClientToGCSelectGuildContractResponse_k_eInternalError

func (m *CMsgClientToGCSelectGuildContractResponse) GetResult() CMsgClientToGCSelectGuildContractResponse_EResponse {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgClientToGCSelectGuildContractResponse_Result
}

type CMsgClientToGCRequestActiveGuildChallenge struct {
	GuildId              *uint32  `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent  `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCRequestActiveGuildChallenge) Reset() {
	*m = CMsgClientToGCRequestActiveGuildChallenge{}
}
func (m *CMsgClientToGCRequestActiveGuildChallenge) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCRequestActiveGuildChallenge) ProtoMessage() {}
func (*CMsgClientToGCRequestActiveGuildChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{14}
}

func (m *CMsgClientToGCRequestActiveGuildChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallenge.Unmarshal(m, b)
}
func (m *CMsgClientToGCRequestActiveGuildChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallenge.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCRequestActiveGuildChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallenge.Merge(m, src)
}
func (m *CMsgClientToGCRequestActiveGuildChallenge) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallenge.Size(m)
}
func (m *CMsgClientToGCRequestActiveGuildChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallenge proto.InternalMessageInfo

const Default_CMsgClientToGCRequestActiveGuildChallenge_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgClientToGCRequestActiveGuildChallenge) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgClientToGCRequestActiveGuildChallenge) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgClientToGCRequestActiveGuildChallenge_EventId
}

type CMsgClientToGCRequestActiveGuildChallengeResponse struct {
	Result               *CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse `protobuf:"varint,1,opt,name=result,enum=protocol.CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse,def=0" json:"result,omitempty"`
	ActiveChallenge      *CMsgGuildChallenge                                          `protobuf:"bytes,2,opt,name=active_challenge,json=activeChallenge" json:"active_challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) Reset() {
	*m = CMsgClientToGCRequestActiveGuildChallengeResponse{}
}
func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCRequestActiveGuildChallengeResponse) ProtoMessage() {}
func (*CMsgClientToGCRequestActiveGuildChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{15}
}

func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallengeResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallengeResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallengeResponse.Merge(m, src)
}
func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallengeResponse.Size(m)
}
func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCRequestActiveGuildChallengeResponse proto.InternalMessageInfo

const Default_CMsgClientToGCRequestActiveGuildChallengeResponse_Result CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse = CMsgClientToGCRequestActiveGuildChallengeResponse_k_eInternalError

func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) GetResult() CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgClientToGCRequestActiveGuildChallengeResponse_Result
}

func (m *CMsgClientToGCRequestActiveGuildChallengeResponse) GetActiveChallenge() *CMsgGuildChallenge {
	if m != nil {
		return m.ActiveChallenge
	}
	return nil
}

type CMsgGCToClientActiveGuildChallengeUpdated struct {
	GuildId              *uint32             `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent             `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	ActiveChallenge      *CMsgGuildChallenge `protobuf:"bytes,3,opt,name=active_challenge,json=activeChallenge" json:"active_challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CMsgGCToClientActiveGuildChallengeUpdated) Reset() {
	*m = CMsgGCToClientActiveGuildChallengeUpdated{}
}
func (m *CMsgGCToClientActiveGuildChallengeUpdated) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgGCToClientActiveGuildChallengeUpdated) ProtoMessage() {}
func (*CMsgGCToClientActiveGuildChallengeUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{16}
}

func (m *CMsgGCToClientActiveGuildChallengeUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCToClientActiveGuildChallengeUpdated.Unmarshal(m, b)
}
func (m *CMsgGCToClientActiveGuildChallengeUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCToClientActiveGuildChallengeUpdated.Marshal(b, m, deterministic)
}
func (m *CMsgGCToClientActiveGuildChallengeUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCToClientActiveGuildChallengeUpdated.Merge(m, src)
}
func (m *CMsgGCToClientActiveGuildChallengeUpdated) XXX_Size() int {
	return xxx_messageInfo_CMsgGCToClientActiveGuildChallengeUpdated.Size(m)
}
func (m *CMsgGCToClientActiveGuildChallengeUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCToClientActiveGuildChallengeUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCToClientActiveGuildChallengeUpdated proto.InternalMessageInfo

const Default_CMsgGCToClientActiveGuildChallengeUpdated_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgGCToClientActiveGuildChallengeUpdated) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgGCToClientActiveGuildChallengeUpdated) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgGCToClientActiveGuildChallengeUpdated_EventId
}

func (m *CMsgGCToClientActiveGuildChallengeUpdated) GetActiveChallenge() *CMsgGuildChallenge {
	if m != nil {
		return m.ActiveChallenge
	}
	return nil
}

type CMsgClientToGCRequestGuildEventMembers struct {
	GuildId              *uint32  `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent  `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCRequestGuildEventMembers) Reset() {
	*m = CMsgClientToGCRequestGuildEventMembers{}
}
func (m *CMsgClientToGCRequestGuildEventMembers) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCRequestGuildEventMembers) ProtoMessage()    {}
func (*CMsgClientToGCRequestGuildEventMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{17}
}

func (m *CMsgClientToGCRequestGuildEventMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCRequestGuildEventMembers.Unmarshal(m, b)
}
func (m *CMsgClientToGCRequestGuildEventMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCRequestGuildEventMembers.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCRequestGuildEventMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCRequestGuildEventMembers.Merge(m, src)
}
func (m *CMsgClientToGCRequestGuildEventMembers) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCRequestGuildEventMembers.Size(m)
}
func (m *CMsgClientToGCRequestGuildEventMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCRequestGuildEventMembers.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCRequestGuildEventMembers proto.InternalMessageInfo

const Default_CMsgClientToGCRequestGuildEventMembers_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgClientToGCRequestGuildEventMembers) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgClientToGCRequestGuildEventMembers) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgClientToGCRequestGuildEventMembers_EventId
}

type CMsgClientToGCRequestGuildEventMembersResponse struct {
	Result               *CMsgClientToGCRequestGuildEventMembersResponse_EResponse `protobuf:"varint,1,opt,name=result,enum=protocol.CMsgClientToGCRequestGuildEventMembersResponse_EResponse,def=0" json:"result,omitempty"`
	Members              []*CMsgGuildEventMember                                   `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *CMsgClientToGCRequestGuildEventMembersResponse) Reset() {
	*m = CMsgClientToGCRequestGuildEventMembersResponse{}
}
func (m *CMsgClientToGCRequestGuildEventMembersResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCRequestGuildEventMembersResponse) ProtoMessage() {}
func (*CMsgClientToGCRequestGuildEventMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{18}
}

func (m *CMsgClientToGCRequestGuildEventMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCRequestGuildEventMembersResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCRequestGuildEventMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCRequestGuildEventMembersResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCRequestGuildEventMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCRequestGuildEventMembersResponse.Merge(m, src)
}
func (m *CMsgClientToGCRequestGuildEventMembersResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCRequestGuildEventMembersResponse.Size(m)
}
func (m *CMsgClientToGCRequestGuildEventMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCRequestGuildEventMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCRequestGuildEventMembersResponse proto.InternalMessageInfo

const Default_CMsgClientToGCRequestGuildEventMembersResponse_Result CMsgClientToGCRequestGuildEventMembersResponse_EResponse = CMsgClientToGCRequestGuildEventMembersResponse_k_eInternalError

func (m *CMsgClientToGCRequestGuildEventMembersResponse) GetResult() CMsgClientToGCRequestGuildEventMembersResponse_EResponse {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgClientToGCRequestGuildEventMembersResponse_Result
}

func (m *CMsgClientToGCRequestGuildEventMembersResponse) GetMembers() []*CMsgGuildEventMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type CMsgGuildLeaderboardCombinedResponse struct {
	EventId              *EEvent                                       `protobuf:"varint,1,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	Region               *uint32                                       `protobuf:"varint,2,opt,name=region" json:"region,omitempty"`
	LastUpdated          *uint32                                       `protobuf:"varint,3,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
	Entries              []*CMsgGuildLeaderboardCombinedResponse_Entry `protobuf:"bytes,4,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *CMsgGuildLeaderboardCombinedResponse) Reset()         { *m = CMsgGuildLeaderboardCombinedResponse{} }
func (m *CMsgGuildLeaderboardCombinedResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgGuildLeaderboardCombinedResponse) ProtoMessage()    {}
func (*CMsgGuildLeaderboardCombinedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{19}
}

func (m *CMsgGuildLeaderboardCombinedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse.Unmarshal(m, b)
}
func (m *CMsgGuildLeaderboardCombinedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse.Marshal(b, m, deterministic)
}
func (m *CMsgGuildLeaderboardCombinedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse.Merge(m, src)
}
func (m *CMsgGuildLeaderboardCombinedResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse.Size(m)
}
func (m *CMsgGuildLeaderboardCombinedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse proto.InternalMessageInfo

const Default_CMsgGuildLeaderboardCombinedResponse_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgGuildLeaderboardCombinedResponse) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgGuildLeaderboardCombinedResponse_EventId
}

func (m *CMsgGuildLeaderboardCombinedResponse) GetRegion() uint32 {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return 0
}

func (m *CMsgGuildLeaderboardCombinedResponse) GetLastUpdated() uint32 {
	if m != nil && m.LastUpdated != nil {
		return *m.LastUpdated
	}
	return 0
}

func (m *CMsgGuildLeaderboardCombinedResponse) GetEntries() []*CMsgGuildLeaderboardCombinedResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type CMsgGuildLeaderboardCombinedResponse_Entry struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	R                    *uint32  `protobuf:"varint,2,opt,name=r" json:"r,omitempty"`
	C                    *uint32  `protobuf:"varint,3,opt,name=c" json:"c,omitempty"`
	W                    *uint32  `protobuf:"varint,4,opt,name=w" json:"w,omitempty"`
	P                    *uint32  `protobuf:"varint,5,opt,name=p" json:"p,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGuildLeaderboardCombinedResponse_Entry) Reset() {
	*m = CMsgGuildLeaderboardCombinedResponse_Entry{}
}
func (m *CMsgGuildLeaderboardCombinedResponse_Entry) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgGuildLeaderboardCombinedResponse_Entry) ProtoMessage() {}
func (*CMsgGuildLeaderboardCombinedResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{19, 0}
}

func (m *CMsgGuildLeaderboardCombinedResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse_Entry.Unmarshal(m, b)
}
func (m *CMsgGuildLeaderboardCombinedResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse_Entry.Marshal(b, m, deterministic)
}
func (m *CMsgGuildLeaderboardCombinedResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse_Entry.Merge(m, src)
}
func (m *CMsgGuildLeaderboardCombinedResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse_Entry.Size(m)
}
func (m *CMsgGuildLeaderboardCombinedResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGuildLeaderboardCombinedResponse_Entry proto.InternalMessageInfo

func (m *CMsgGuildLeaderboardCombinedResponse_Entry) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CMsgGuildLeaderboardCombinedResponse_Entry) GetR() uint32 {
	if m != nil && m.R != nil {
		return *m.R
	}
	return 0
}

func (m *CMsgGuildLeaderboardCombinedResponse_Entry) GetC() uint32 {
	if m != nil && m.C != nil {
		return *m.C
	}
	return 0
}

func (m *CMsgGuildLeaderboardCombinedResponse_Entry) GetW() uint32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *CMsgGuildLeaderboardCombinedResponse_Entry) GetP() uint32 {
	if m != nil && m.P != nil {
		return *m.P
	}
	return 0
}

type CMsgGuildLeaderboardCombinedResponseV2 struct {
	EventId              *EEvent  `protobuf:"varint,1,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	Region               *uint32  `protobuf:"varint,2,opt,name=region" json:"region,omitempty"`
	LastUpdated          *uint32  `protobuf:"varint,3,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
	Id                   []uint32 `protobuf:"varint,4,rep,packed,name=id" json:"id,omitempty"`
	R                    []uint32 `protobuf:"varint,5,rep,packed,name=r" json:"r,omitempty"`
	C                    []uint32 `protobuf:"varint,6,rep,packed,name=c" json:"c,omitempty"`
	W                    []uint32 `protobuf:"varint,7,rep,packed,name=w" json:"w,omitempty"`
	P                    []uint32 `protobuf:"varint,8,rep,packed,name=p" json:"p,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) Reset() {
	*m = CMsgGuildLeaderboardCombinedResponseV2{}
}
func (m *CMsgGuildLeaderboardCombinedResponseV2) String() string { return proto.CompactTextString(m) }
func (*CMsgGuildLeaderboardCombinedResponseV2) ProtoMessage()    {}
func (*CMsgGuildLeaderboardCombinedResponseV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{20}
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponseV2.Unmarshal(m, b)
}
func (m *CMsgGuildLeaderboardCombinedResponseV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponseV2.Marshal(b, m, deterministic)
}
func (m *CMsgGuildLeaderboardCombinedResponseV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGuildLeaderboardCombinedResponseV2.Merge(m, src)
}
func (m *CMsgGuildLeaderboardCombinedResponseV2) XXX_Size() int {
	return xxx_messageInfo_CMsgGuildLeaderboardCombinedResponseV2.Size(m)
}
func (m *CMsgGuildLeaderboardCombinedResponseV2) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGuildLeaderboardCombinedResponseV2.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGuildLeaderboardCombinedResponseV2 proto.InternalMessageInfo

const Default_CMsgGuildLeaderboardCombinedResponseV2_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgGuildLeaderboardCombinedResponseV2) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgGuildLeaderboardCombinedResponseV2_EventId
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) GetRegion() uint32 {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return 0
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) GetLastUpdated() uint32 {
	if m != nil && m.LastUpdated != nil {
		return *m.LastUpdated
	}
	return 0
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) GetId() []uint32 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) GetR() []uint32 {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) GetC() []uint32 {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) GetW() []uint32 {
	if m != nil {
		return m.W
	}
	return nil
}

func (m *CMsgGuildLeaderboardCombinedResponseV2) GetP() []uint32 {
	if m != nil {
		return m.P
	}
	return nil
}

type CMsgClientToGCClaimLeaderboardRewards struct {
	GuildId              *uint32  `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventId              *EEvent  `protobuf:"varint,2,opt,name=event_id,json=eventId,enum=protocol.EEvent,def=0" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgClientToGCClaimLeaderboardRewards) Reset()         { *m = CMsgClientToGCClaimLeaderboardRewards{} }
func (m *CMsgClientToGCClaimLeaderboardRewards) String() string { return proto.CompactTextString(m) }
func (*CMsgClientToGCClaimLeaderboardRewards) ProtoMessage()    {}
func (*CMsgClientToGCClaimLeaderboardRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{21}
}

func (m *CMsgClientToGCClaimLeaderboardRewards) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewards.Unmarshal(m, b)
}
func (m *CMsgClientToGCClaimLeaderboardRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewards.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCClaimLeaderboardRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewards.Merge(m, src)
}
func (m *CMsgClientToGCClaimLeaderboardRewards) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewards.Size(m)
}
func (m *CMsgClientToGCClaimLeaderboardRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewards.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewards proto.InternalMessageInfo

const Default_CMsgClientToGCClaimLeaderboardRewards_EventId EEvent = EEvent_EVENT_ID_NONE

func (m *CMsgClientToGCClaimLeaderboardRewards) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgClientToGCClaimLeaderboardRewards) GetEventId() EEvent {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return Default_CMsgClientToGCClaimLeaderboardRewards_EventId
}

type CMsgClientToGCClaimLeaderboardRewardsResponse struct {
	Result               *CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse `protobuf:"varint,1,opt,name=result,enum=protocol.CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse,def=0" json:"result,omitempty"`
	EventPoints          *uint32                                                  `protobuf:"varint,2,opt,name=event_points,json=eventPoints" json:"event_points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) Reset() {
	*m = CMsgClientToGCClaimLeaderboardRewardsResponse{}
}
func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientToGCClaimLeaderboardRewardsResponse) ProtoMessage() {}
func (*CMsgClientToGCClaimLeaderboardRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e89b9d2b17d423b2, []int{22}
}

func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewardsResponse.Unmarshal(m, b)
}
func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewardsResponse.Marshal(b, m, deterministic)
}
func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewardsResponse.Merge(m, src)
}
func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewardsResponse.Size(m)
}
func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgClientToGCClaimLeaderboardRewardsResponse proto.InternalMessageInfo

const Default_CMsgClientToGCClaimLeaderboardRewardsResponse_Result CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse = CMsgClientToGCClaimLeaderboardRewardsResponse_k_eInternalError

func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) GetResult() CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgClientToGCClaimLeaderboardRewardsResponse_Result
}

func (m *CMsgClientToGCClaimLeaderboardRewardsResponse) GetEventPoints() uint32 {
	if m != nil && m.EventPoints != nil {
		return *m.EventPoints
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.EGuildEventAuditAction", EGuildEventAuditAction_name, EGuildEventAuditAction_value)
	proto.RegisterEnum("protocol.CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse", CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse_name, CMsgClientToGCRequestAccountGuildEventDataResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCRequestActiveGuildContractsResponse_EResponse", CMsgClientToGCRequestActiveGuildContractsResponse_EResponse_name, CMsgClientToGCRequestActiveGuildContractsResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCSelectGuildContractResponse_EResponse", CMsgClientToGCSelectGuildContractResponse_EResponse_name, CMsgClientToGCSelectGuildContractResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse", CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse_name, CMsgClientToGCRequestActiveGuildChallengeResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCRequestGuildEventMembersResponse_EResponse", CMsgClientToGCRequestGuildEventMembersResponse_EResponse_name, CMsgClientToGCRequestGuildEventMembersResponse_EResponse_value)
	proto.RegisterEnum("protocol.CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse", CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse_name, CMsgClientToGCClaimLeaderboardRewardsResponse_EResponse_value)
	proto.RegisterType((*CMsgGuildContract)(nil), "protocol.CMsgGuildContract")
	proto.RegisterType((*CMsgGuildContractSlot)(nil), "protocol.CMsgGuildContractSlot")
	proto.RegisterType((*CMsgAccountGuildEventData)(nil), "protocol.CMsgAccountGuildEventData")
	proto.RegisterType((*CMsgGuildActiveContracts)(nil), "protocol.CMsgGuildActiveContracts")
	proto.RegisterType((*CMsgGuildChallenge)(nil), "protocol.CMsgGuildChallenge")
	proto.RegisterType((*CMsgGuildEventMember)(nil), "protocol.CMsgGuildEventMember")
	proto.RegisterType((*CMsgClientToGCRequestAccountGuildEventData)(nil), "protocol.CMsgClientToGCRequestAccountGuildEventData")
	proto.RegisterType((*CMsgClientToGCRequestAccountGuildEventDataResponse)(nil), "protocol.CMsgClientToGCRequestAccountGuildEventDataResponse")
	proto.RegisterType((*CMsgGCToClientAccountGuildEventDataUpdated)(nil), "protocol.CMsgGCToClientAccountGuildEventDataUpdated")
	proto.RegisterType((*CMsgClientToGCRequestActiveGuildContracts)(nil), "protocol.CMsgClientToGCRequestActiveGuildContracts")
	proto.RegisterType((*CMsgClientToGCRequestActiveGuildContractsResponse)(nil), "protocol.CMsgClientToGCRequestActiveGuildContractsResponse")
	proto.RegisterType((*CMsgGCToClientActiveGuildContractsUpdated)(nil), "protocol.CMsgGCToClientActiveGuildContractsUpdated")
	proto.RegisterType((*CMsgClientToGCSelectGuildContract)(nil), "protocol.CMsgClientToGCSelectGuildContract")
	proto.RegisterType((*CMsgClientToGCSelectGuildContractResponse)(nil), "protocol.CMsgClientToGCSelectGuildContractResponse")
	proto.RegisterType((*CMsgClientToGCRequestActiveGuildChallenge)(nil), "protocol.CMsgClientToGCRequestActiveGuildChallenge")
	proto.RegisterType((*CMsgClientToGCRequestActiveGuildChallengeResponse)(nil), "protocol.CMsgClientToGCRequestActiveGuildChallengeResponse")
	proto.RegisterType((*CMsgGCToClientActiveGuildChallengeUpdated)(nil), "protocol.CMsgGCToClientActiveGuildChallengeUpdated")
	proto.RegisterType((*CMsgClientToGCRequestGuildEventMembers)(nil), "protocol.CMsgClientToGCRequestGuildEventMembers")
	proto.RegisterType((*CMsgClientToGCRequestGuildEventMembersResponse)(nil), "protocol.CMsgClientToGCRequestGuildEventMembersResponse")
	proto.RegisterType((*CMsgGuildLeaderboardCombinedResponse)(nil), "protocol.CMsgGuildLeaderboardCombinedResponse")
	proto.RegisterType((*CMsgGuildLeaderboardCombinedResponse_Entry)(nil), "protocol.CMsgGuildLeaderboardCombinedResponse.Entry")
	proto.RegisterType((*CMsgGuildLeaderboardCombinedResponseV2)(nil), "protocol.CMsgGuildLeaderboardCombinedResponseV2")
	proto.RegisterType((*CMsgClientToGCClaimLeaderboardRewards)(nil), "protocol.CMsgClientToGCClaimLeaderboardRewards")
	proto.RegisterType((*CMsgClientToGCClaimLeaderboardRewardsResponse)(nil), "protocol.CMsgClientToGCClaimLeaderboardRewardsResponse")
}

func init() {
	proto.RegisterFile("dota_gcmessages_client_guild_events.proto", fileDescriptor_e89b9d2b17d423b2)
}

var fileDescriptor_e89b9d2b17d423b2 = []byte{
	// 1685 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcf, 0x53, 0x1b, 0xd7,
	0x1d, 0xf7, 0x4a, 0x80, 0xc4, 0x57, 0x20, 0x96, 0x87, 0x01, 0x01, 0x76, 0x0d, 0x6b, 0xbb, 0xc5,
	0x6e, 0x51, 0x6b, 0xb5, 0xd3, 0xba, 0xcc, 0x78, 0xa6, 0x20, 0x64, 0xaa, 0x19, 0xc0, 0x54, 0xa6,
	0xf6, 0x71, 0xe7, 0xb1, 0xfb, 0x2c, 0x76, 0xb4, 0xda, 0x55, 0xf7, 0xad, 0x60, 0xb8, 0xb4, 0x1d,
	0xf7, 0xdc, 0x53, 0x4e, 0x39, 0x26, 0xa7, 0x9c, 0x72, 0xc9, 0x25, 0xa7, 0x4c, 0xee, 0xf9, 0x2b,
	0x72, 0xc9, 0x9f, 0x90, 0x99, 0x4c, 0x2e, 0x99, 0xf7, 0x6b, 0x77, 0xb5, 0x48, 0x42, 0x24, 0xd1,
	0x64, 0x38, 0x49, 0xfb, 0xfd, 0xf5, 0xbe, 0x3f, 0x3f, 0xef, 0x07, 0x3c, 0xb1, 0xfd, 0x10, 0x9b,
	0x4d, 0xab, 0x4d, 0x28, 0xc5, 0x4d, 0x42, 0x4d, 0xcb, 0x75, 0x88, 0x17, 0x9a, 0xcd, 0xae, 0xe3,
	0xda, 0x26, 0x39, 0x27, 0x5e, 0x48, 0xcb, 0x9d, 0xc0, 0x0f, 0x7d, 0x94, 0xe7, 0x3f, 0x96, 0xef,
	0xae, 0x2e, 0x73, 0x25, 0x7a, 0x86, 0x03, 0x62, 0x9b, 0xc4, 0xeb, 0xb6, 0xa5, 0x88, 0xf1, 0x51,
	0x06, 0xe6, 0xab, 0x87, 0xb4, 0xb9, 0xcf, 0xb4, 0xab, 0xbe, 0x17, 0x06, 0xd8, 0x0a, 0xd1, 0x03,
	0x28, 0x58, 0xf2, 0xbf, 0xe9, 0xd8, 0x25, 0x6d, 0x5d, 0xdb, 0x9c, 0x68, 0x80, 0x22, 0xd5, 0x6d,
	0x54, 0x81, 0x45, 0xeb, 0x0c, 0xbb, 0x2e, 0xf1, 0x9a, 0xc4, 0x74, 0x3c, 0x1a, 0x62, 0xcf, 0x22,
	0x4c, 0x34, 0xb3, 0xae, 0x6d, 0xce, 0x36, 0x16, 0x22, 0x66, 0x5d, 0xf2, 0xea, 0x36, 0xfa, 0x3d,
	0xc4, 0x64, 0xb3, 0x83, 0x03, 0xdc, 0x26, 0x21, 0x09, 0x4a, 0x59, 0xae, 0x81, 0x22, 0xd6, 0xb1,
	0xe2, 0xf4, 0x2a, 0x84, 0x4e, 0x9b, 0xd0, 0x10, 0xb7, 0x3b, 0xa5, 0x89, 0x94, 0xc2, 0x89, 0xe2,
	0xa0, 0x32, 0x2c, 0x60, 0x4a, 0x9d, 0xa6, 0x47, 0x6c, 0x13, 0x5b, 0x96, 0xdf, 0xf5, 0xb8, 0xfb,
	0x93, 0x5c, 0x61, 0x5e, 0xb1, 0x76, 0x04, 0xa7, 0x6e, 0xa3, 0xc7, 0x50, 0x8c, 0xc2, 0x7c, 0xe7,
	0xe2, 0x26, 0x2d, 0x4d, 0x71, 0xd1, 0x59, 0x45, 0x7d, 0xc9, 0x88, 0xc6, 0x31, 0x2c, 0x5e, 0x49,
	0xd1, 0x6b, 0xd7, 0x0f, 0xd1, 0x5f, 0x20, 0xaf, 0x24, 0x79, 0x8e, 0x0a, 0x95, 0xb5, 0xb2, 0x4a,
	0x79, 0xf9, 0x8a, 0x4a, 0x23, 0x12, 0x36, 0x3e, 0x9d, 0x80, 0x15, 0xc6, 0x97, 0xae, 0x70, 0xb1,
	0x1a, 0xab, 0xdc, 0x1e, 0x0e, 0x31, 0xda, 0x80, 0x19, 0x51, 0xcc, 0x8e, 0xef, 0x78, 0x21, 0xe5,
	0xa6, 0x67, 0x1b, 0x05, 0x4e, 0x3b, 0xe6, 0x24, 0xb4, 0x0b, 0xf7, 0x95, 0x31, 0x6a, 0x06, 0xe4,
	0x5d, 0x40, 0xe8, 0x19, 0xb1, 0x13, 0x49, 0x12, 0x75, 0x58, 0x8b, 0x84, 0x1a, 0x4a, 0x26, 0xce,
	0xd6, 0xcb, 0x44, 0xf4, 0xd4, 0xf5, 0x43, 0x5a, 0xca, 0xae, 0x67, 0x37, 0x0b, 0x95, 0x07, 0x43,
	0x62, 0x60, 0x61, 0xc7, 0xe9, 0x61, 0x5f, 0x14, 0x6d, 0xc3, 0x8a, 0xe5, 0xb7, 0x3b, 0x2e, 0x09,
	0x89, 0x6d, 0xc6, 0x05, 0xe3, 0x91, 0xc9, 0x62, 0x2d, 0x47, 0x02, 0x55, 0xc5, 0xaf, 0x32, 0x36,
	0xfa, 0x1b, 0xdc, 0x8b, 0x34, 0xa2, 0x40, 0x12, 0x61, 0x88, 0xd2, 0xad, 0xc6, 0x32, 0x32, 0x8e,
	0x38, 0x8a, 0x3f, 0xc3, 0xb2, 0x48, 0xd6, 0x05, 0x21, 0x2d, 0xf7, 0xd2, 0xec, 0x90, 0xc0, 0x22,
	0x5e, 0xe8, 0xb8, 0x44, 0x16, 0x73, 0x91, 0xb3, 0xdf, 0x72, 0xee, 0x71, 0xc4, 0x44, 0x2f, 0x60,
	0xad, 0x47, 0xcf, 0xc5, 0x34, 0x4c, 0x2c, 0x9c, 0xe3, 0xba, 0xa5, 0x84, 0xee, 0x01, 0xa6, 0x61,
	0xbc, 0xec, 0x1f, 0x61, 0x89, 0x6b, 0x48, 0x6d, 0xcb, 0xc5, 0x4e, 0x9b, 0xab, 0x97, 0xf2, 0x62,
	0x02, 0x18, 0x57, 0x28, 0x56, 0x19, 0x8f, 0x69, 0xa2, 0xe7, 0x20, 0x0c, 0x9a, 0x56, 0x37, 0x08,
	0xd8, 0xcc, 0x26, 0x9c, 0x9d, 0xe6, 0x6a, 0x4b, 0x9c, 0x5f, 0x15, 0xec, 0xd8, 0x5b, 0xe3, 0x43,
	0x0d, 0x4a, 0x51, 0x31, 0x76, 0xac, 0xd0, 0x39, 0x27, 0xaa, 0x24, 0x23, 0x34, 0x83, 0x76, 0x7d,
	0x33, 0xfc, 0x15, 0xa6, 0x23, 0x76, 0x29, 0xc3, 0xfb, 0x60, 0x68, 0x2f, 0xc7, 0xd2, 0xc6, 0xfb,
	0x0c, 0xa0, 0x58, 0x40, 0x55, 0x6a, 0x30, 0x44, 0x68, 0x37, 0x86, 0x88, 0xcc, 0x4d, 0x21, 0x22,
	0x3b, 0x10, 0x22, 0xb6, 0x00, 0x25, 0x56, 0x08, 0xfc, 0x66, 0x40, 0x28, 0x95, 0x5d, 0x3a, 0x1f,
	0x2f, 0x20, 0x19, 0xe8, 0x37, 0x30, 0x17, 0x8b, 0x0b, 0x88, 0x10, 0x2d, 0x59, 0x8c, 0xc8, 0x02,
	0x23, 0x08, 0xdc, 0x8d, 0x72, 0xc0, 0x27, 0xf9, 0x90, 0xb4, 0x4f, 0x49, 0x80, 0xee, 0x03, 0x24,
	0x90, 0x48, 0x84, 0x3e, 0x8d, 0x23, 0x04, 0x2a, 0xc3, 0x42, 0x72, 0xd4, 0x4d, 0x82, 0x03, 0x8f,
	0x28, 0x14, 0x9d, 0x4f, 0x4c, 0x7c, 0x8d, 0x33, 0x8c, 0xff, 0x69, 0xf0, 0x94, 0xad, 0x53, 0xe5,
	0x98, 0x7f, 0xe2, 0xef, 0x57, 0x1b, 0xe4, 0x5f, 0x5d, 0x42, 0xc3, 0xfe, 0x48, 0xb2, 0x02, 0x79,
	0x61, 0x3e, 0x5a, 0x3b, 0xc7, 0xbf, 0xeb, 0x36, 0xda, 0x86, 0x3c, 0xdf, 0x2b, 0x14, 0x68, 0x17,
	0x2b, 0x7a, 0x5c, 0xef, 0x1a, 0x37, 0xb1, 0x3d, 0x5b, 0x7b, 0x53, 0x3b, 0x3a, 0x31, 0xeb, 0x7b,
	0xe6, 0xd1, 0xab, 0xa3, 0x5a, 0x23, 0xc7, 0x15, 0xea, 0xb6, 0xf1, 0x75, 0x16, 0x2a, 0xa3, 0x7b,
	0xd1, 0x20, 0xb4, 0xe3, 0x7b, 0x94, 0xa0, 0x0e, 0x4c, 0x05, 0x84, 0x76, 0x5d, 0x01, 0x96, 0xc5,
	0xca, 0xcb, 0xde, 0x06, 0xbb, 0x99, 0xb5, 0x72, 0x4d, 0xfd, 0xdb, 0xd6, 0x5b, 0x26, 0xa9, 0x7b,
	0x21, 0x09, 0x3c, 0xec, 0xd6, 0x82, 0xc0, 0x0f, 0x1a, 0x72, 0x9d, 0x9f, 0x12, 0x24, 0xda, 0x05,
	0x10, 0xba, 0x36, 0x0e, 0x31, 0xef, 0xa8, 0x42, 0xe5, 0x61, 0xaf, 0xc7, 0xfd, 0x1d, 0x9c, 0x26,
	0xea, 0xaf, 0xf1, 0xb9, 0x06, 0xd3, 0x91, 0x9f, 0xe8, 0x2e, 0x5c, 0xf1, 0x54, 0xbf, 0x83, 0x8a,
	0x00, 0x2d, 0x93, 0xbc, 0xee, 0x5a, 0x16, 0xa1, 0x54, 0xd7, 0xe4, 0xf7, 0x89, 0xef, 0xef, 0x76,
	0xe9, 0xa5, 0x9e, 0x41, 0x73, 0x50, 0x68, 0x99, 0x64, 0xcf, 0xa1, 0xf8, 0xd4, 0x25, 0xb6, 0x9e,
	0x55, 0x02, 0x4e, 0x9b, 0xf8, 0xdd, 0x50, 0x9f, 0x40, 0x0b, 0x30, 0xc7, 0xcd, 0x9e, 0x63, 0xd7,
	0x11, 0x6e, 0xe8, 0x93, 0xbd, 0x44, 0xee, 0xa0, 0x3e, 0x85, 0x74, 0x98, 0x69, 0x99, 0xe4, 0xc8,
	0x97, 0xcd, 0xa9, 0xe7, 0x50, 0x09, 0xee, 0xa6, 0xc4, 0x84, 0x81, 0xbc, 0xf1, 0x71, 0x46, 0x74,
	0xda, 0x7e, 0xf5, 0xc4, 0x17, 0x95, 0xe9, 0x1b, 0xed, 0x3f, 0x3b, 0x36, 0x0e, 0x89, 0x3d, 0xa6,
	0x4e, 0x63, 0x5b, 0x61, 0x97, 0xaf, 0x20, 0x87, 0x4f, 0x0c, 0x76, 0x41, 0xd0, 0xf8, 0xe4, 0xa1,
	0x43, 0xd0, 0x13, 0x47, 0x1f, 0x51, 0xad, 0x89, 0xd1, 0xab, 0x55, 0x6c, 0xf6, 0x8e, 0xcc, 0x6f,
	0x61, 0x3e, 0x06, 0x53, 0xb1, 0x8e, 0x38, 0x41, 0xe4, 0x1b, 0x7a, 0xc4, 0x90, 0x51, 0x1b, 0xef,
	0x35, 0x78, 0x32, 0xa0, 0x75, 0x19, 0x44, 0xf7, 0x40, 0x26, 0x1d, 0xd7, 0x34, 0x7e, 0x97, 0x85,
	0x67, 0x23, 0x3b, 0x11, 0x35, 0xa3, 0x9f, 0x1a, 0xc6, 0xda, 0xb5, 0xc3, 0x38, 0xd8, 0xd8, 0x48,
	0xb3, 0x78, 0x08, 0x3a, 0xe6, 0x36, 0xcc, 0xe4, 0x46, 0xc3, 0xea, 0x64, 0xf4, 0xd9, 0x68, 0x52,
	0x7b, 0x5c, 0x63, 0x0e, 0xa7, 0x36, 0xbd, 0x3a, 0xcc, 0x2b, 0x73, 0xd1, 0xe1, 0x40, 0x4e, 0xe9,
	0xbd, 0x7e, 0x1b, 0x97, 0x12, 0x6a, 0x48, 0x2f, 0x22, 0x02, 0xbd, 0xcd, 0x53, 0xaa, 0x1a, 0x30,
	0x39, 0xa5, 0x57, 0xeb, 0x34, 0xde, 0x21, 0x35, 0xbe, 0xd4, 0x60, 0xa3, 0xb7, 0x67, 0x5e, 0x13,
	0x97, 0x58, 0x61, 0xef, 0x9d, 0x62, 0x4c, 0x08, 0x91, 0xba, 0xaa, 0x64, 0xaf, 0x5c, 0x55, 0x1e,
	0xc2, 0x6c, 0xcf, 0x31, 0x57, 0x6e, 0xf6, 0x33, 0xc9, 0x43, 0xac, 0xf1, 0xff, 0x89, 0xf4, 0x20,
	0xf7, 0x09, 0x21, 0x6a, 0x91, 0x66, 0x6a, 0x76, 0x5e, 0x0c, 0x9a, 0x9d, 0x21, 0x46, 0x46, 0x99,
	0x19, 0xe3, 0xdb, 0xcc, 0x6d, 0xed, 0xcc, 0x5e, 0x8e, 0x0a, 0xbe, 0xbe, 0xa7, 0x4f, 0xa3, 0x25,
	0x40, 0x2d, 0x93, 0xec, 0xb8, 0x01, 0xc1, 0xf6, 0xe5, 0x8e, 0xbc, 0x94, 0xe9, 0x80, 0x56, 0x61,
	0xe9, 0xaa, 0x06, 0xab, 0x8e, 0x5e, 0x40, 0x2b, 0xb0, 0xd8, 0x32, 0x49, 0x92, 0x78, 0xe0, 0x5b,
	0x2d, 0x62, 0xeb, 0x33, 0x68, 0x0d, 0x96, 0x53, 0xac, 0xaa, 0xef, 0xbb, 0xb6, 0x7f, 0xe1, 0xe9,
	0xb3, 0xd2, 0x0b, 0xc5, 0xdc, 0xeb, 0x76, 0x5c, 0xc7, 0xc2, 0x21, 0xd1, 0x8b, 0xe8, 0x1e, 0x94,
	0x52, 0x6a, 0x2c, 0x23, 0x22, 0xa9, 0x73, 0xa3, 0x01, 0x7b, 0x74, 0xd4, 0x1d, 0xd3, 0x5c, 0x7d,
	0x32, 0x0a, 0xb0, 0x47, 0xb8, 0xf6, 0x73, 0x00, 0x7b, 0xda, 0xd8, 0x48, 0xc0, 0xbe, 0x1f, 0x03,
	0xbb, 0xd2, 0x97, 0xc0, 0x3e, 0x1c, 0x88, 0xe7, 0x52, 0x40, 0x7c, 0x9b, 0x71, 0xf8, 0xab, 0xa1,
	0x38, 0xac, 0x22, 0x1c, 0xf3, 0x61, 0xa9, 0x5f, 0x21, 0xb2, 0x3f, 0xa6, 0x10, 0xff, 0x81, 0x5f,
	0xf7, 0x6d, 0x95, 0xf4, 0xed, 0x66, 0x6c, 0x47, 0x9a, 0x0f, 0xb2, 0x50, 0x1e, 0xcd, 0x83, 0xa8,
	0x5d, 0xdc, 0x54, 0xdb, 0xef, 0x5e, 0xd3, 0xf6, 0x03, 0x2d, 0x8d, 0xd4, 0xf3, 0xcf, 0x21, 0xd7,
	0x16, 0x6a, 0xf2, 0xb2, 0xfc, 0xab, 0x3e, 0x19, 0x4e, 0x58, 0x6f, 0x28, 0xf1, 0xdb, 0xdc, 0xe4,
	0x5f, 0x64, 0xe0, 0x51, 0x14, 0xdc, 0x01, 0xc1, 0x36, 0x09, 0x4e, 0x7d, 0x1c, 0xd8, 0x55, 0xbf,
	0x7d, 0xea, 0x78, 0xc4, 0x8e, 0xa2, 0x4a, 0x96, 0x5e, 0xbb, 0x61, 0x13, 0x2f, 0xb1, 0x3a, 0x36,
	0x1d, 0xdf, 0x93, 0x97, 0x60, 0xf9, 0xc5, 0x6e, 0x02, 0xfc, 0xc1, 0x45, 0x1d, 0xc9, 0xe5, 0x4d,
	0x80, 0xd1, 0xd4, 0x58, 0x1d, 0x41, 0x8e, 0x78, 0x61, 0xe0, 0x10, 0x76, 0xa1, 0x67, 0x45, 0xf9,
	0x53, 0x9f, 0xa2, 0x0c, 0xf1, 0xbb, 0x5c, 0xf3, 0xc2, 0xe0, 0xb2, 0xa1, 0x8c, 0xac, 0xbe, 0x82,
	0x49, 0x4e, 0x41, 0x45, 0xc8, 0x44, 0xfd, 0x9d, 0x71, 0x6c, 0x34, 0x03, 0x9a, 0x7a, 0x94, 0xd0,
	0x02, 0xf6, 0x65, 0x49, 0x77, 0x34, 0x8b, 0x7d, 0x5d, 0xc8, 0x23, 0x86, 0x76, 0xc1, 0xbe, 0xd4,
	0x23, 0x96, 0xd6, 0x31, 0xbe, 0xd7, 0xc4, 0x60, 0x5d, 0xe7, 0xc8, 0x9b, 0xca, 0x2f, 0x95, 0x42,
	0xc4, 0x23, 0x65, 0xd9, 0x9b, 0xdd, 0xcd, 0xe8, 0x1a, 0x8f, 0x56, 0x67, 0xd1, 0x4e, 0x46, 0x24,
	0x2d, 0x60, 0x14, 0xab, 0x34, 0x15, 0x53, 0x2c, 0x46, 0xb9, 0x28, 0xe5, 0x62, 0xca, 0x05, 0xa3,
	0x74, 0x4a, 0xf9, 0x98, 0xd2, 0x31, 0xfe, 0x0d, 0x8f, 0x7b, 0x27, 0x91, 0x3f, 0x8c, 0x25, 0xd2,
	0xd0, 0x20, 0x17, 0x38, 0xb0, 0xe9, 0x18, 0xb7, 0xd3, 0xad, 0x91, 0x1c, 0x88, 0xfa, 0xb8, 0x95,
	0xc2, 0x94, 0x9d, 0x41, 0x98, 0x72, 0x8d, 0xa1, 0x91, 0x20, 0x65, 0x03, 0x66, 0x44, 0x68, 0xf2,
	0xd5, 0x57, 0xd4, 0xae, 0xc0, 0x69, 0xe2, 0x0d, 0xc8, 0xf8, 0xe6, 0xd6, 0x62, 0x07, 0x5a, 0x84,
	0x79, 0xb6, 0xac, 0x4f, 0xe8, 0x91, 0x1f, 0xfe, 0xa3, 0x8b, 0x5d, 0xe7, 0xdd, 0xa5, 0x3e, 0x2d,
	0xc9, 0xf2, 0x2c, 0xc8, 0xb3, 0xc8, 0x8e, 0x82, 0x4f, 0x3f, 0xcb, 0xc2, 0x52, 0x2d, 0xd6, 0xdf,
	0xe9, 0xda, 0x0e, 0xdf, 0x50, 0x7d, 0x0f, 0x3d, 0x82, 0xf5, 0x96, 0xd9, 0x9f, 0x67, 0xca, 0x85,
	0xf5, 0x3b, 0xe8, 0x31, 0x6c, 0x0c, 0x94, 0xda, 0x23, 0xe7, 0xfb, 0x01, 0xf6, 0x42, 0x5d, 0x43,
	0x5b, 0xf0, 0x64, 0xa0, 0x58, 0x55, 0x3e, 0x59, 0xab, 0x23, 0xa2, 0x9e, 0x41, 0x65, 0x78, 0x7a,
	0xbd, 0xb8, 0xda, 0x45, 0xf5, 0x2c, 0x7a, 0x06, 0x5b, 0xd7, 0xca, 0x1f, 0xe2, 0xd0, 0x3a, 0x33,
	0xdf, 0x3a, 0x9e, 0x47, 0x02, 0x7d, 0x62, 0xf8, 0x12, 0xe9, 0xe7, 0x49, 0x7d, 0x12, 0xfd, 0x01,
	0x7e, 0x37, 0xe2, 0x12, 0x07, 0x3e, 0x25, 0x81, 0x3e, 0x35, 0x74, 0x05, 0xf9, 0xd2, 0x1d, 0x37,
	0xb2, 0x9e, 0x43, 0x9b, 0xf0, 0x68, 0xa0, 0xfc, 0x21, 0xf6, 0xba, 0xd8, 0x15, 0xd9, 0xcc, 0xef,
	0x4e, 0xfe, 0x5d, 0xfb, 0xaf, 0x76, 0xe7, 0x87, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xac, 0x25,
	0xb6, 0xa1, 0x1a, 0x00, 0x00,
}
