// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.14.0
// source: github.com/paralin/go-dota2/protocol/econ_shared_enums.proto

package protocol

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
)

type EGCEconBaseMsg int32

const (
	EGCEconBaseMsg_k_EMsgGCGenericResult EGCEconBaseMsg = 2579
)

// Enum value maps for EGCEconBaseMsg.
var (
	EGCEconBaseMsg_name = map[int32]string{
		2579: "k_EMsgGCGenericResult",
	}
	EGCEconBaseMsg_value = map[string]int32{
		"k_EMsgGCGenericResult": 2579,
	}
)

func (x EGCEconBaseMsg) Enum() *EGCEconBaseMsg {
	p := new(EGCEconBaseMsg)
	*p = x
	return p
}

func (x EGCEconBaseMsg) String() string {
	name, valid := EGCEconBaseMsg_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

type EGCMsgResponse int32

const (
	EGCMsgResponse_k_EGCMsgResponseOK           EGCMsgResponse = 0
	EGCMsgResponse_k_EGCMsgResponseDenied       EGCMsgResponse = 1
	EGCMsgResponse_k_EGCMsgResponseServerError  EGCMsgResponse = 2
	EGCMsgResponse_k_EGCMsgResponseTimeout      EGCMsgResponse = 3
	EGCMsgResponse_k_EGCMsgResponseInvalid      EGCMsgResponse = 4
	EGCMsgResponse_k_EGCMsgResponseNoMatch      EGCMsgResponse = 5
	EGCMsgResponse_k_EGCMsgResponseUnknownError EGCMsgResponse = 6
	EGCMsgResponse_k_EGCMsgResponseNotLoggedOn  EGCMsgResponse = 7
	EGCMsgResponse_k_EGCMsgFailedToCreate       EGCMsgResponse = 8
)

// Enum value maps for EGCMsgResponse.
var (
	EGCMsgResponse_name = map[int32]string{
		0: "k_EGCMsgResponseOK",
		1: "k_EGCMsgResponseDenied",
		2: "k_EGCMsgResponseServerError",
		3: "k_EGCMsgResponseTimeout",
		4: "k_EGCMsgResponseInvalid",
		5: "k_EGCMsgResponseNoMatch",
		6: "k_EGCMsgResponseUnknownError",
		7: "k_EGCMsgResponseNotLoggedOn",
		8: "k_EGCMsgFailedToCreate",
	}
	EGCMsgResponse_value = map[string]int32{
		"k_EGCMsgResponseOK":           0,
		"k_EGCMsgResponseDenied":       1,
		"k_EGCMsgResponseServerError":  2,
		"k_EGCMsgResponseTimeout":      3,
		"k_EGCMsgResponseInvalid":      4,
		"k_EGCMsgResponseNoMatch":      5,
		"k_EGCMsgResponseUnknownError": 6,
		"k_EGCMsgResponseNotLoggedOn":  7,
		"k_EGCMsgFailedToCreate":       8,
	}
)

func (x EGCMsgResponse) Enum() *EGCMsgResponse {
	p := new(EGCMsgResponse)
	*p = x
	return p
}

func (x EGCMsgResponse) String() string {
	name, valid := EGCMsgResponse_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

type EGCMsgUseItemResponse int32

const (
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed                    EGCMsgUseItemResponse = 0
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_GiftNoOtherPlayers          EGCMsgUseItemResponse = 1
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ServerError                 EGCMsgUseItemResponse = 2
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_MiniGameAlreadyStarted      EGCMsgUseItemResponse = 3
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted       EGCMsgUseItemResponse = 4
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted EGCMsgUseItemResponse = 5
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_NotInLowPriorityPool        EGCMsgUseItemResponse = 6
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_NotHighEnoughLevel          EGCMsgUseItemResponse = 7
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EventNotActive              EGCMsgUseItemResponse = 8
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted EGCMsgUseItemResponse = 9
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_MissingRequirement          EGCMsgUseItemResponse = 10
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew        EGCMsgUseItemResponse = 11
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EmoticonUnlock_Complete     EGCMsgUseItemResponse = 12
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_Compendium         EGCMsgUseItemResponse = 13
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_CannotUseWhileUntradable    EGCMsgUseItemResponse = 14
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_CannotBeUsedByAccount       EGCMsgUseItemResponse = 15
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_RecipientCannotRecieve      EGCMsgUseItemResponse = 16
)

// Enum value maps for EGCMsgUseItemResponse.
var (
	EGCMsgUseItemResponse_name = map[int32]string{
		0:  "k_EGCMsgUseItemResponse_ItemUsed",
		1:  "k_EGCMsgUseItemResponse_GiftNoOtherPlayers",
		2:  "k_EGCMsgUseItemResponse_ServerError",
		3:  "k_EGCMsgUseItemResponse_MiniGameAlreadyStarted",
		4:  "k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted",
		5:  "k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted",
		6:  "k_EGCMsgUseItemResponse_NotInLowPriorityPool",
		7:  "k_EGCMsgUseItemResponse_NotHighEnoughLevel",
		8:  "k_EGCMsgUseItemResponse_EventNotActive",
		9:  "k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted",
		10: "k_EGCMsgUseItemResponse_MissingRequirement",
		11: "k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew",
		12: "k_EGCMsgUseItemResponse_EmoticonUnlock_Complete",
		13: "k_EGCMsgUseItemResponse_ItemUsed_Compendium",
		14: "k_EGCMsgUseItemResponse_CannotUseWhileUntradable",
		15: "k_EGCMsgUseItemResponse_CannotBeUsedByAccount",
		16: "k_EGCMsgUseItemResponse_RecipientCannotRecieve",
	}
	EGCMsgUseItemResponse_value = map[string]int32{
		"k_EGCMsgUseItemResponse_ItemUsed":                    0,
		"k_EGCMsgUseItemResponse_GiftNoOtherPlayers":          1,
		"k_EGCMsgUseItemResponse_ServerError":                 2,
		"k_EGCMsgUseItemResponse_MiniGameAlreadyStarted":      3,
		"k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted":       4,
		"k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted": 5,
		"k_EGCMsgUseItemResponse_NotInLowPriorityPool":        6,
		"k_EGCMsgUseItemResponse_NotHighEnoughLevel":          7,
		"k_EGCMsgUseItemResponse_EventNotActive":              8,
		"k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted": 9,
		"k_EGCMsgUseItemResponse_MissingRequirement":          10,
		"k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew":        11,
		"k_EGCMsgUseItemResponse_EmoticonUnlock_Complete":     12,
		"k_EGCMsgUseItemResponse_ItemUsed_Compendium":         13,
		"k_EGCMsgUseItemResponse_CannotUseWhileUntradable":    14,
		"k_EGCMsgUseItemResponse_CannotBeUsedByAccount":       15,
		"k_EGCMsgUseItemResponse_RecipientCannotRecieve":      16,
	}
)

func (x EGCMsgUseItemResponse) Enum() *EGCMsgUseItemResponse {
	p := new(EGCMsgUseItemResponse)
	*p = x
	return p
}

func (x EGCMsgUseItemResponse) String() string {
	name, valid := EGCMsgUseItemResponse_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

type CMsgGenericResult struct {
	unknownFields []byte
	Eresult       *uint32 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	DebugMessage  *string `protobuf:"bytes,2,opt,name=debug_message,json=debugMessage" json:"debugMessage,omitempty"`
}

// Default values for CMsgGenericResult fields.
const (
	Default_CMsgGenericResult_Eresult = uint32(2)
)

func (x *CMsgGenericResult) Reset() {
	*x = CMsgGenericResult{}
}

func (*CMsgGenericResult) ProtoMessage() {}

func (x *CMsgGenericResult) GetEresult() uint32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgGenericResult_Eresult
}

func (x *CMsgGenericResult) GetDebugMessage() string {
	if x != nil && x.DebugMessage != nil {
		return *x.DebugMessage
	}
	return ""
}

func (m *CMsgGenericResult) CloneVT() *CMsgGenericResult {
	if m == nil {
		return (*CMsgGenericResult)(nil)
	}
	r := new(CMsgGenericResult)
	if rhs := m.Eresult; rhs != nil {
		tmpVal := *rhs
		r.Eresult = &tmpVal
	}
	if rhs := m.DebugMessage; rhs != nil {
		tmpVal := *rhs
		r.DebugMessage = &tmpVal
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *CMsgGenericResult) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *CMsgGenericResult) EqualVT(that *CMsgGenericResult) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Eresult, that.Eresult; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.DebugMessage, that.DebugMessage; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CMsgGenericResult) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*CMsgGenericResult)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// NOTE: protobuf-go-lite json only supports proto3 and editions: proto2 is not supported.

func (m *CMsgGenericResult) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CMsgGenericResult) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *CMsgGenericResult) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.DebugMessage != nil {
		i -= len(*m.DebugMessage)
		copy(dAtA[i:], *m.DebugMessage)
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(len(*m.DebugMessage)))
		i--
		dAtA[i] = 0x12
	}
	if m.Eresult != nil {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(*m.Eresult))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CMsgGenericResult) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Eresult != nil {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(*m.Eresult))
	}
	if m.DebugMessage != nil {
		l = len(*m.DebugMessage)
		n += 1 + l + protobuf_go_lite.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (x EGCEconBaseMsg) MarshalProtoText() string {
	return x.String()
}

func (x EGCMsgResponse) MarshalProtoText() string {
	return x.String()
}

func (x EGCMsgUseItemResponse) MarshalProtoText() string {
	return x.String()
}

func (x *CMsgGenericResult) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("CMsgGenericResult {")
	if x.Eresult != nil {
		if sb.Len() > 19 {
			sb.WriteString(" ")
		}
		sb.WriteString("eresult: ")
		sb.WriteString(strconv.FormatUint(uint64(*x.Eresult), 10))
	}
	if x.DebugMessage != nil {
		if sb.Len() > 19 {
			sb.WriteString(" ")
		}
		sb.WriteString("debug_message: ")
		sb.WriteString(strconv.Quote(*x.DebugMessage))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *CMsgGenericResult) String() string {
	return x.MarshalProtoText()
}

func (m *CMsgGenericResult) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CMsgGenericResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CMsgGenericResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eresult", wireType)
			}
			var v uint32
			v, iNdEx, err = protobuf_go_lite.DecodeVarintUint32(dAtA, iNdEx)
			if err != nil {
				return err
			}
			m.Eresult = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebugMessage", wireType)
			}
			var stringLen uint64
			stringLen, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			if err != nil {
				return err
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DebugMessage = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
