// Code generated by protoc-gen-go. DO NOT EDIT.
// source: econ_shared_enums.proto

package econ_shared_enums

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EGCEconBaseMsg int32

const (
	EGCEconBaseMsg_k_EMsgGCGenericResult EGCEconBaseMsg = 2579
)

var EGCEconBaseMsg_name = map[int32]string{
	2579: "k_EMsgGCGenericResult",
}
var EGCEconBaseMsg_value = map[string]int32{
	"k_EMsgGCGenericResult": 2579,
}

func (x EGCEconBaseMsg) Enum() *EGCEconBaseMsg {
	p := new(EGCEconBaseMsg)
	*p = x
	return p
}
func (x EGCEconBaseMsg) String() string {
	return proto.EnumName(EGCEconBaseMsg_name, int32(x))
}
func (x *EGCEconBaseMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCEconBaseMsg_value, data, "EGCEconBaseMsg")
	if err != nil {
		return err
	}
	*x = EGCEconBaseMsg(value)
	return nil
}
func (EGCEconBaseMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EGCMsgResponse int32

const (
	EGCMsgResponse_k_EGCMsgResponseOK           EGCMsgResponse = 0
	EGCMsgResponse_k_EGCMsgResponseDenied       EGCMsgResponse = 1
	EGCMsgResponse_k_EGCMsgResponseServerError  EGCMsgResponse = 2
	EGCMsgResponse_k_EGCMsgResponseTimeout      EGCMsgResponse = 3
	EGCMsgResponse_k_EGCMsgResponseInvalid      EGCMsgResponse = 4
	EGCMsgResponse_k_EGCMsgResponseNoMatch      EGCMsgResponse = 5
	EGCMsgResponse_k_EGCMsgResponseUnknownError EGCMsgResponse = 6
	EGCMsgResponse_k_EGCMsgResponseNotLoggedOn  EGCMsgResponse = 7
	EGCMsgResponse_k_EGCMsgFailedToCreate       EGCMsgResponse = 8
)

var EGCMsgResponse_name = map[int32]string{
	0: "k_EGCMsgResponseOK",
	1: "k_EGCMsgResponseDenied",
	2: "k_EGCMsgResponseServerError",
	3: "k_EGCMsgResponseTimeout",
	4: "k_EGCMsgResponseInvalid",
	5: "k_EGCMsgResponseNoMatch",
	6: "k_EGCMsgResponseUnknownError",
	7: "k_EGCMsgResponseNotLoggedOn",
	8: "k_EGCMsgFailedToCreate",
}
var EGCMsgResponse_value = map[string]int32{
	"k_EGCMsgResponseOK":           0,
	"k_EGCMsgResponseDenied":       1,
	"k_EGCMsgResponseServerError":  2,
	"k_EGCMsgResponseTimeout":      3,
	"k_EGCMsgResponseInvalid":      4,
	"k_EGCMsgResponseNoMatch":      5,
	"k_EGCMsgResponseUnknownError": 6,
	"k_EGCMsgResponseNotLoggedOn":  7,
	"k_EGCMsgFailedToCreate":       8,
}

func (x EGCMsgResponse) Enum() *EGCMsgResponse {
	p := new(EGCMsgResponse)
	*p = x
	return p
}
func (x EGCMsgResponse) String() string {
	return proto.EnumName(EGCMsgResponse_name, int32(x))
}
func (x *EGCMsgResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCMsgResponse_value, data, "EGCMsgResponse")
	if err != nil {
		return err
	}
	*x = EGCMsgResponse(value)
	return nil
}
func (EGCMsgResponse) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EGCPartnerRequestResponse int32

const (
	EGCPartnerRequestResponse_k_EPartnerRequestOK                     EGCPartnerRequestResponse = 1
	EGCPartnerRequestResponse_k_EPartnerRequestBadAccount             EGCPartnerRequestResponse = 2
	EGCPartnerRequestResponse_k_EPartnerRequestNotLinked              EGCPartnerRequestResponse = 3
	EGCPartnerRequestResponse_k_EPartnerRequestUnsupportedPartnerType EGCPartnerRequestResponse = 4
)

var EGCPartnerRequestResponse_name = map[int32]string{
	1: "k_EPartnerRequestOK",
	2: "k_EPartnerRequestBadAccount",
	3: "k_EPartnerRequestNotLinked",
	4: "k_EPartnerRequestUnsupportedPartnerType",
}
var EGCPartnerRequestResponse_value = map[string]int32{
	"k_EPartnerRequestOK":                     1,
	"k_EPartnerRequestBadAccount":             2,
	"k_EPartnerRequestNotLinked":              3,
	"k_EPartnerRequestUnsupportedPartnerType": 4,
}

func (x EGCPartnerRequestResponse) Enum() *EGCPartnerRequestResponse {
	p := new(EGCPartnerRequestResponse)
	*p = x
	return p
}
func (x EGCPartnerRequestResponse) String() string {
	return proto.EnumName(EGCPartnerRequestResponse_name, int32(x))
}
func (x *EGCPartnerRequestResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCPartnerRequestResponse_value, data, "EGCPartnerRequestResponse")
	if err != nil {
		return err
	}
	*x = EGCPartnerRequestResponse(value)
	return nil
}
func (EGCPartnerRequestResponse) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EGCMsgUseItemResponse int32

const (
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed                    EGCMsgUseItemResponse = 0
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_GiftNoOtherPlayers          EGCMsgUseItemResponse = 1
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ServerError                 EGCMsgUseItemResponse = 2
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_MiniGameAlreadyStarted      EGCMsgUseItemResponse = 3
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted       EGCMsgUseItemResponse = 4
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted EGCMsgUseItemResponse = 5
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_NotInLowPriorityPool        EGCMsgUseItemResponse = 6
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_NotHighEnoughLevel          EGCMsgUseItemResponse = 7
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EventNotActive              EGCMsgUseItemResponse = 8
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted EGCMsgUseItemResponse = 9
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_MissingRequirement          EGCMsgUseItemResponse = 10
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew        EGCMsgUseItemResponse = 11
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_EmoticonUnlock_Complete     EGCMsgUseItemResponse = 12
	EGCMsgUseItemResponse_k_EGCMsgUseItemResponse_ItemUsed_Compendium         EGCMsgUseItemResponse = 13
)

var EGCMsgUseItemResponse_name = map[int32]string{
	0:  "k_EGCMsgUseItemResponse_ItemUsed",
	1:  "k_EGCMsgUseItemResponse_GiftNoOtherPlayers",
	2:  "k_EGCMsgUseItemResponse_ServerError",
	3:  "k_EGCMsgUseItemResponse_MiniGameAlreadyStarted",
	4:  "k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted",
	5:  "k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted",
	6:  "k_EGCMsgUseItemResponse_NotInLowPriorityPool",
	7:  "k_EGCMsgUseItemResponse_NotHighEnoughLevel",
	8:  "k_EGCMsgUseItemResponse_EventNotActive",
	9:  "k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted",
	10: "k_EGCMsgUseItemResponse_MissingRequirement",
	11: "k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew",
	12: "k_EGCMsgUseItemResponse_EmoticonUnlock_Complete",
	13: "k_EGCMsgUseItemResponse_ItemUsed_Compendium",
}
var EGCMsgUseItemResponse_value = map[string]int32{
	"k_EGCMsgUseItemResponse_ItemUsed":                    0,
	"k_EGCMsgUseItemResponse_GiftNoOtherPlayers":          1,
	"k_EGCMsgUseItemResponse_ServerError":                 2,
	"k_EGCMsgUseItemResponse_MiniGameAlreadyStarted":      3,
	"k_EGCMsgUseItemResponse_ItemUsed_ItemsGranted":       4,
	"k_EGCMsgUseItemResponse_DropRateBonusAlreadyGranted": 5,
	"k_EGCMsgUseItemResponse_NotInLowPriorityPool":        6,
	"k_EGCMsgUseItemResponse_NotHighEnoughLevel":          7,
	"k_EGCMsgUseItemResponse_EventNotActive":              8,
	"k_EGCMsgUseItemResponse_ItemUsed_EventPointsGranted": 9,
	"k_EGCMsgUseItemResponse_MissingRequirement":          10,
	"k_EGCMsgUseItemResponse_EmoticonUnlock_NoNew":        11,
	"k_EGCMsgUseItemResponse_EmoticonUnlock_Complete":     12,
	"k_EGCMsgUseItemResponse_ItemUsed_Compendium":         13,
}

func (x EGCMsgUseItemResponse) Enum() *EGCMsgUseItemResponse {
	p := new(EGCMsgUseItemResponse)
	*p = x
	return p
}
func (x EGCMsgUseItemResponse) String() string {
	return proto.EnumName(EGCMsgUseItemResponse_name, int32(x))
}
func (x *EGCMsgUseItemResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCMsgUseItemResponse_value, data, "EGCMsgUseItemResponse")
	if err != nil {
		return err
	}
	*x = EGCMsgUseItemResponse(value)
	return nil
}
func (EGCMsgUseItemResponse) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CMsgGenericResult struct {
	Eresult          *uint32 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	DebugMessage     *string `protobuf:"bytes,2,opt,name=debug_message,json=debugMessage" json:"debug_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGenericResult) Reset()                    { *m = CMsgGenericResult{} }
func (m *CMsgGenericResult) String() string            { return proto.CompactTextString(m) }
func (*CMsgGenericResult) ProtoMessage()               {}
func (*CMsgGenericResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_CMsgGenericResult_Eresult uint32 = 2

func (m *CMsgGenericResult) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgGenericResult_Eresult
}

func (m *CMsgGenericResult) GetDebugMessage() string {
	if m != nil && m.DebugMessage != nil {
		return *m.DebugMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*CMsgGenericResult)(nil), "CMsgGenericResult")
	proto.RegisterEnum("EGCEconBaseMsg", EGCEconBaseMsg_name, EGCEconBaseMsg_value)
	proto.RegisterEnum("EGCMsgResponse", EGCMsgResponse_name, EGCMsgResponse_value)
	proto.RegisterEnum("EGCPartnerRequestResponse", EGCPartnerRequestResponse_name, EGCPartnerRequestResponse_value)
	proto.RegisterEnum("EGCMsgUseItemResponse", EGCMsgUseItemResponse_name, EGCMsgUseItemResponse_value)
}

func init() { proto.RegisterFile("econ_shared_enums.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xc6, 0x81, 0xf0, 0x33, 0x17, 0xae, 0xe6, 0xce, 0xbd, 0xfc, 0x5c, 0xa8, 0xda, 0xa8, 0x54,
	0x05, 0x05, 0x0a, 0x2d, 0x2c, 0x2a, 0x75, 0x47, 0x82, 0x1b, 0x10, 0xc4, 0x89, 0x02, 0x59, 0x5b,
	0x53, 0xfb, 0xd4, 0x19, 0xc5, 0x3e, 0xc7, 0x9d, 0x19, 0x07, 0x65, 0xd7, 0x77, 0xe8, 0xb2, 0xbb,
	0xbe, 0x4b, 0xdf, 0xab, 0x72, 0x80, 0xa8, 0x09, 0x24, 0x74, 0x37, 0xfe, 0x7e, 0x74, 0xbe, 0xef,
	0x1c, 0xb3, 0x75, 0x08, 0x08, 0x7d, 0xd3, 0x91, 0x1a, 0x42, 0x1f, 0x30, 0x4b, 0xcc, 0x41, 0xaa,
	0xc9, 0xd2, 0xcb, 0x36, 0xfb, 0xa7, 0x5a, 0x37, 0x51, 0x0d, 0x10, 0xb4, 0x0a, 0x5a, 0x60, 0xb2,
	0xd8, 0x8a, 0x2d, 0xb6, 0x00, 0x7a, 0xf0, 0xdc, 0x70, 0x4a, 0xce, 0xee, 0xca, 0x07, 0xe7, 0xa8,
	0x75, 0x8f, 0x88, 0x6d, 0xb6, 0x12, 0xc2, 0xa7, 0x2c, 0xf2, 0x13, 0x30, 0x46, 0x46, 0xb0, 0x51,
	0x28, 0x39, 0xbb, 0x4b, 0xad, 0xe5, 0x01, 0x58, 0xbf, 0xc5, 0xca, 0xfb, 0xec, 0x6f, 0xb7, 0x56,
	0x75, 0x03, 0xc2, 0x8a, 0x34, 0x50, 0x37, 0x91, 0xd8, 0x64, 0xab, 0x5d, 0xdf, 0xcd, 0x47, 0x55,
	0x47, 0x86, 0xf1, 0x6f, 0xff, 0x95, 0xbf, 0x17, 0x06, 0xf2, 0xba, 0x89, 0x5a, 0x60, 0x52, 0x42,
	0x03, 0x62, 0x8d, 0x89, 0xae, 0x3f, 0x8a, 0x35, 0x2e, 0xf8, 0x8c, 0xd8, 0x64, 0x6b, 0xe3, 0xf8,
	0x29, 0xa0, 0x82, 0x90, 0x3b, 0xe2, 0x05, 0xdb, 0x1a, 0xe7, 0xae, 0x40, 0xf7, 0x40, 0xbb, 0x5a,
	0x93, 0xe6, 0x05, 0xb1, 0xc5, 0xd6, 0xc7, 0x05, 0xd7, 0x2a, 0x01, 0xca, 0x2c, 0x9f, 0x7d, 0x8c,
	0x3c, 0xc7, 0x9e, 0x8c, 0x55, 0xc8, 0xe7, 0x1e, 0x23, 0x3d, 0xaa, 0x4b, 0x1b, 0x74, 0x78, 0x51,
	0x94, 0xd8, 0xb3, 0x71, 0xb2, 0x8d, 0x5d, 0xa4, 0x1b, 0xbc, 0x1d, 0x3c, 0xff, 0x58, 0x32, 0x8f,
	0xec, 0x25, 0x45, 0x11, 0x84, 0x0d, 0xe4, 0x0b, 0xbf, 0xd7, 0xfa, 0x28, 0x55, 0x0c, 0xe1, 0x35,
	0x55, 0x35, 0x48, 0x0b, 0x7c, 0xb1, 0xfc, 0xc3, 0x61, 0xff, 0xbb, 0xb5, 0x6a, 0x53, 0x6a, 0x8b,
	0xa0, 0x5b, 0xf0, 0x25, 0x03, 0x63, 0x87, 0x8b, 0x5a, 0x67, 0xff, 0x76, 0x7d, 0x77, 0x94, 0x6c,
	0x5c, 0x0c, 0xb7, 0x31, 0x4a, 0x54, 0x64, 0x78, 0x12, 0x04, 0x94, 0xa1, 0xe5, 0x05, 0xf1, 0x9c,
	0x6d, 0x3e, 0x10, 0xe4, 0xa9, 0x14, 0x76, 0x21, 0xe4, 0xb3, 0x62, 0x8f, 0xed, 0x3c, 0xe0, 0xdb,
	0x68, 0xb2, 0x34, 0x25, 0x6d, 0x21, 0xbc, 0x23, 0xae, 0xfb, 0x29, 0xf0, 0xb9, 0xf2, 0xcf, 0x22,
	0x5b, 0xbd, 0xcd, 0xdf, 0x36, 0x70, 0x6e, 0x21, 0x19, 0x06, 0x7c, 0xc5, 0x4a, 0xf7, 0xd5, 0xc6,
	0x28, 0x3f, 0xff, 0x68, 0x1b, 0x08, 0xf9, 0x8c, 0x38, 0x60, 0xe5, 0x49, 0xaa, 0x9a, 0xfa, 0x6c,
	0x3d, 0x6a, 0xd8, 0x0e, 0xe8, 0x66, 0x2c, 0xfb, 0xa0, 0x0d, 0x77, 0xc4, 0x0e, 0xdb, 0x9e, 0xa4,
	0x1f, 0xbd, 0xf9, 0x11, 0x3b, 0x98, 0x24, 0xac, 0x2b, 0x54, 0x35, 0x99, 0xc0, 0x49, 0xac, 0x41,
	0x86, 0xfd, 0x2b, 0x2b, 0xf3, 0x5e, 0x7c, 0x56, 0xbc, 0x63, 0x6f, 0x9e, 0x8a, 0x3c, 0x78, 0x98,
	0x9a, 0x96, 0x98, 0x5b, 0xe6, 0xc4, 0x7b, 0x76, 0x3c, 0xc9, 0x72, 0xaa, 0x29, 0x6d, 0x49, 0x0b,
	0x15, 0xc2, 0xcc, 0xdc, 0xcd, 0xba, 0x37, 0x16, 0xc5, 0x5b, 0xb6, 0x3f, 0xc9, 0xe8, 0x91, 0x3d,
	0xc7, 0x4b, 0xba, 0x69, 0x6a, 0x45, 0x5a, 0xd9, 0x7e, 0x93, 0x28, 0xe6, 0xf3, 0xd3, 0x56, 0xe5,
	0x91, 0x3d, 0x53, 0x51, 0xc7, 0x45, 0xca, 0xa2, 0xce, 0x25, 0xf4, 0x20, 0xe6, 0x0b, 0xa2, 0xcc,
	0x5e, 0x4f, 0xd2, 0xbb, 0x3d, 0xc0, 0xfc, 0xe6, 0x27, 0x81, 0x55, 0x3d, 0xe0, 0x8b, 0xd3, 0x6a,
	0x0c, 0x9b, 0x0f, 0x4c, 0x4d, 0x52, 0x68, 0x87, 0xfd, 0x97, 0xa6, 0x85, 0xaa, 0x2b, 0x63, 0x14,
	0x46, 0xf9, 0x1f, 0xa4, 0x34, 0x24, 0x80, 0x96, 0xb3, 0x69, 0xb5, 0xdd, 0x84, 0xac, 0x0a, 0x08,
	0xdb, 0x18, 0x53, 0xd0, 0xf5, 0x3d, 0xf2, 0xe0, 0x86, 0xff, 0x25, 0x8e, 0xd9, 0xe1, 0x1f, 0x3a,
	0xaa, 0x94, 0xa4, 0x31, 0x58, 0xe0, 0xcb, 0xe2, 0x90, 0xed, 0x3d, 0xd9, 0x27, 0x97, 0x03, 0x86,
	0x2a, 0x4b, 0xf8, 0x4a, 0xa5, 0x78, 0xe6, 0x7c, 0x75, 0x66, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x20, 0x62, 0x5e, 0xeb, 0x30, 0x05, 0x00, 0x00,
}
